#Reading Loan Dataset

In [ ]:
df_loan = pd.read_csv("C:/Users/admin/Downloads/datasets/loan_portfolio_dataset.csv")

In [2]:
import pandas as pd
import numpy as np

In [6]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_id                800000 non-null  int64
 1   customer_segment       800000 non-null  str
 2   sanction_amount        800000 non-null  int64
 3   outstanding_principal  800000 non-null  int64
 4   interest_rate          800000 non-null  float64
 5   repricing_frequency    800000 non-null  str
 6   prepayment_option      800000 non-null  str
 7   collateral_type        800000 non-null  str
 8   region                 800000 non-null  str
 9   tenure_months          800000 non-null  int64
dtypes: float64(1), int64(4), str(5)
memory usage: 61.0 MB

In [7]:
df_loan.head()

,loan_id,customer_segment,sanction_amount,outstanding_principal,interest_rate,repricing_frequency,prepayment_option,collateral_type,region,tenure_months
0,1,Corporate,4473539,1399755,12.44,Monthly,No,Secured,Central,144
1,2,Retail,2598113,1509414,8.52,Half-Yearly,Yes,Secured,North,18
2,3,Corporate,2448830,3963945,10.73,Quarterly,No,Unsecured,East,51
3,4,Corporate,3136211,3933227,14.59,Half-Yearly,No,Unsecured,East,21
4,5,Retail,3840012,1414890,7.56,Monthly,Yes,Secured,North,91

In [8]:
df_loan.tail()

,loan_id,customer_segment,sanction_amount,outstanding_principal,interest_rate,repricing_frequency,prepayment_option,collateral_type,region,tenure_months
799995,799996,SME,3680256,1827723,8.46,Half-Yearly,No,Unsecured,South,135
799996,799997,Retail,4514389,3717405,11.78,Quarterly,Yes,Secured,East,139
799997,799998,Retail,1811402,1035235,7.23,Quarterly,No,Secured,North,15
799998,799999,Retail,1589116,572950,8.15,Monthly,Yes,Secured,Central,109
799999,800000,SME,2625570,1629175,16.26,Half-Yearly,Yes,Unsecured,East,173

In [9]:
df_loan.shape

(800000, 10)

In [10]:
df_loan.columns

Index(['loan_id', 'customer_segment', 'sanction_amount',
       'outstanding_principal', 'interest_rate', 'repricing_frequency',
       'prepayment_option', 'collateral_type', 'region', 'tenure_months'],
      dtype='str')

In [11]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_id                800000 non-null  int64
 1   customer_segment       800000 non-null  str
 2   sanction_amount        800000 non-null  int64
 3   outstanding_principal  800000 non-null  int64
 4   interest_rate          800000 non-null  float64
 5   repricing_frequency    800000 non-null  str
 6   prepayment_option      800000 non-null  str
 7   collateral_type        800000 non-null  str
 8   region                 800000 non-null  str
 9   tenure_months          800000 non-null  int64
dtypes: float64(1), int64(4), str(5)
memory usage: 61.0 MB

In [12]:
df_loan.describe()

,loan_id,sanction_amount,outstanding_principal,interest_rate,tenure_months
count,800000.000000,8.000000e+05,8.000000e+05,800000.000000,800000.000000
mean,400000.500000,2.523013e+06,2.004313e+06,12.496878,125.485942
std,230940.252013,1.430761e+06,1.151454e+06,3.175649,65.827576
min,1.000000,5.000600e+04,1.002000e+04,7.000000,12.000000
25%,200000.750000,1.282186e+06,1.007734e+06,9.750000,68.000000
50%,400000.500000,2.520272e+06,2.003104e+06,12.500000,126.000000
75%,600000.250000,3.762831e+06,3.002133e+06,15.240000,182.000000
max,800000.000000,4.999998e+06,3.999995e+06,18.000000,239.000000

In [13]:
df_loan.shape

(800000, 10)

In [14]:
df_loan.columns

Index(['loan_id', 'customer_segment', 'sanction_amount',
       'outstanding_principal', 'interest_rate', 'repricing_frequency',
       'prepayment_option', 'collateral_type', 'region', 'tenure_months'],
      dtype='str')

In [15]:
df_loan.dtypes

loan_id                    int64
customer_segment             str
sanction_amount            int64
outstanding_principal      int64
interest_rate            float64
repricing_frequency          str
prepayment_option            str
collateral_type              str
region                       str
tenure_months              int64
dtype: object

In [22]:
df_loan["loan_id"].duplicated().sum()

np.int64(0)

In [23]:
df_loan.isnull().sum()

loan_id                  0
customer_segment         0
sanction_amount          0
outstanding_principal    0
interest_rate            0
repricing_frequency      0
prepayment_option        0
collateral_type          0
region                   0
tenure_months            0
dtype: int64

In [26]:
df_loan.isnull().sum()

loan_id                  0
customer_segment         0
sanction_amount          0
outstanding_principal    0
interest_rate            0
repricing_frequency      0
prepayment_option        0
collateral_type          0
region                   0
tenure_months            0
dtype: int64

In [28]:
(df_loan.isnull().sum() / len(df_loan)) * 100

loan_id                  0.0
customer_segment         0.0
sanction_amount          0.0
outstanding_principal    0.0
interest_rate            0.0
repricing_frequency      0.0
prepayment_option        0.0
collateral_type          0.0
region                   0.0
tenure_months            0.0
dtype: float64

In [29]:
df_loan.duplicated().sum()

np.int64(0)

In [33]:

invalid_loan_amount = df_loan[
    (df_loan['loan_amount'] < 0) |  
]
   invalid_interest_rate= df_loan[(df_loan['interest_rate'] < 0) | (df_loan['interest_rate'] > 100)
]

SyntaxError: invalid syntax (3326418691.py, line 3)

In [36]:
invalid_sanction_amount = df_loan[df_loan['sanction_amount'] < 0]
invalid_interest_rate = df_loan[(df_loan['interest_rate'] < 0) | (df_loan['interest_rate'] > 100)]

In [39]:
df_loan.describe()

,loan_id,sanction_amount,outstanding_principal,interest_rate,tenure_months
count,800000.000000,8.000000e+05,8.000000e+05,800000.000000,800000.000000
mean,400000.500000,2.523013e+06,2.004313e+06,12.496878,125.485942
std,230940.252013,1.430761e+06,1.151454e+06,3.175649,65.827576
min,1.000000,5.000600e+04,1.002000e+04,7.000000,12.000000
25%,200000.750000,1.282186e+06,1.007734e+06,9.750000,68.000000
50%,400000.500000,2.520272e+06,2.003104e+06,12.500000,126.000000
75%,600000.250000,3.762831e+06,3.002133e+06,15.240000,182.000000
max,800000.000000,4.999998e+06,3.999995e+06,18.000000,239.000000

In [41]:
df_loan[df_loan["outstanding_principal"] > df_loan["sanction_amount"]]

,loan_id,customer_segment,sanction_amount,outstanding_principal,interest_rate,repricing_frequency,prepayment_option,collateral_type,region,tenure_months
2,3,Corporate,2448830,3963945,10.73,Quarterly,No,Unsecured,East,51
3,4,Corporate,3136211,3933227,14.59,Half-Yearly,No,Unsecured,East,21
7,8,SME,1535130,3332913,15.57,Half-Yearly,Yes,Secured,East,73
11,12,Corporate,1246631,3884670,13.43,Monthly,Yes,Secured,East,206
13,14,Corporate,240386,3987398,8.02,Quarterly,Yes,Secured,North,15
...,...,...,...,...,...,...,...,...,...,...
799982,799983,Corporate,782703,2935936,12.69,Monthly,Yes,Secured,West,196
799984,799985,Corporate,1458279,3506956,15.42,Half-Yearly,Yes,Unsecured,North,124
799986,799987,Corporate,73321,3946723,14.04,Quarterly,Yes,Unsecured,South,157
799989,799990,SME,1271147,3017661,17.61,Half-Yearly,No,Unsecured,Central,233
799990,799991,Corporate,157729,1951818,12.03,Monthly,No,Secured,North,201

In [42]:
df_loan[df_loan["outstanding_principal"] == 0]

Empty DataFrame
Columns: [loan_id, customer_segment, sanction_amount, outstanding_principal, interest_rate, repricing_frequency, prepayment_option, collateral_type, region, tenure_months]
Index: []

In [43]:

Q1 = df_loan["interest_rate"].quantile(0.25)
Q3 = df_loan["interest_rate"].quantile(0.75)
IQR = Q3 - Q1

outliers = df_loan[
    (df_loan["interest_rate"] < Q1 - 1.5 * IQR) |
    (df_loan["interest_rate"] > Q3 + 1.5 * IQR)
]

print(len(outliers))

0

In [49]:
df_loan_clean = df_loan[
    (df_loan["sanction_amount"] > 0) &
    (df_loan["outstanding_principal"] >= 0) &
    (df_loan["outstanding_principal"] <= df_loan["sanction_amount"]) &
    (df_loan["interest_rate"].between(0, 25)) &
    (df_loan["tenure_months"].between(6, 360))
]

In [55]:
print(df_loan_clean)

        loan_id customer_segment  sanction_amount  outstanding_principal  \
0             1        Corporate          4473539                1399755
1             2           Retail          2598113                1509414
4             5           Retail          3840012                1414890
5             6           Retail          3744016                 661621
6             7        Corporate          3036670                2774929
...         ...              ...              ...                    ...
799995   799996              SME          3680256                1827723
799996   799997           Retail          4514389                3717405
799997   799998           Retail          1811402                1035235
799998   799999           Retail          1589116                 572950
799999   800000              SME          2625570                1629175

        interest_rate repricing_frequency prepayment_option collateral_type  \
0               12.44             Monthly                No         Secured
1                8.52         Half-Yearly               Yes         Secured
4                7.56             Monthly               Yes         Secured
5               13.63         Half-Yearly               Yes       Unsecured
6               15.28         Half-Yearly                No         Secured
...               ...                 ...               ...             ...
799995           8.46         Half-Yearly                No       Unsecured
799996          11.78           Quarterly               Yes         Secured
799997           7.23           Quarterly                No         Secured
799998           8.15             Monthly               Yes         Secured
799999          16.26         Half-Yearly               Yes       Unsecured

         region  tenure_months
0       Central            144
1         North             18
4         North             91
5          West             60
6         North            178
...         ...            ...
799995    South            135
799996     East            139
799997    North             15
799998  Central            109
799999     East            173

[483862 rows x 10 columns]

In [57]:
import pandas as pd

df_loan = df_loan.copy()
numeric_cols = df_loan.select_dtypes(include="number").columns

summary = []

for col in numeric_cols:
    Q1 = df_loan[col].quantile(0.25)
    Q3 = df_loan[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df_loan[(df_loan[col] < lower_bound) | (df_loan[col] > upper_bound)]
    
    summary.append({
        "column": col,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "outlier_count": len(outliers),
        "outlier_%": round(len(outliers) / len(df_loan) * 100, 4)
    })

outlier_summary = pd.DataFrame(summary)

outlier_summary

,column,Q1,Q3,IQR,lower_bound,upper_bound,outlier_count,outlier_%
0,loan_id,200000.75,600000.25,399999.50,-399998.500,1199999.500,0,0.0
1,sanction_amount,1282186.00,3762831.00,2480645.00,-2438781.500,7483798.500,0,0.0
2,outstanding_principal,1007734.50,3002132.75,1994398.25,-1983862.875,5993730.125,0,0.0
3,interest_rate,9.75,15.24,5.49,1.515,23.475,0,0.0
4,tenure_months,68.00,182.00,114.00,-103.000,353.000,0,0.0

In [63]:
df_loan['flag_high_interest'] = df_loan['interest_rate'] > 20

In [64]:
print(df_loan['flag_high_interest'])

0         False
1         False
2         False
3         False
4         False
          ...
799995    False
799996    False
799997    False
799998    False
799999    False
Name: flag_high_interest, Length: 800000, dtype: bool

In [65]:
df_loan['flag_invalid_amount'] = df_loan['outstanding_principal'] > df_loan['sanction_amount']

In [66]:
print(df_loan['flag_invalid_amount'])

0         False
1         False
2          True
3          True
4         False
          ...
799995    False
799996    False
799997    False
799998    False
799999    False
Name: flag_invalid_amount, Length: 800000, dtype: bool

In [67]:
df_loan['flag_long_tenure'] = df_loan['tenure_months'] > 120

In [69]:
print(df_loan['flag_long_tenure'])

0          True
1         False
2         False
3         False
4         False
          ...
799995     True
799996     True
799997    False
799998    False
799999     True
Name: flag_long_tenure, Length: 800000, dtype: bool

In [70]:
df_loan['flag_missing'] = df_loan.isnull().any(axis=1)

In [71]:
print(df_loan['flag_missing'])

0         False
1         False
2         False
3         False
4         False
          ...
799995    False
799996    False
799997    False
799998    False
799999    False
Name: flag_missing, Length: 800000, dtype: bool

In [72]:
df_loan['any_violation'] = (
    df_loan['flag_high_interest'] |
    df_loan['flag_invalid_amount'] |
    df_loan['flag_long_tenure'] |
    df_loan['flag_missing']
)

In [73]:
print(df_loan['any_violation'])

0          True
1         False
2          True
3          True
4         False
          ...
799995     True
799996     True
799997    False
799998    False
799999     True
Name: any_violation, Length: 800000, dtype: bool

In [74]:
violations = df_loan[df_loan['any_violation'] == True]

In [75]:
print(violations)

        loan_id customer_segment  sanction_amount  outstanding_principal  \
0             1        Corporate          4473539                1399755
2             3        Corporate          2448830                3963945
3             4        Corporate          3136211                3933227
6             7        Corporate          3036670                2774929
7             8              SME          1535130                3332913
...         ...              ...              ...                    ...
799989   799990              SME          1271147                3017661
799990   799991        Corporate           157729                1951818
799995   799996              SME          3680256                1827723
799996   799997           Retail          4514389                3717405
799999   800000              SME          2625570                1629175

        interest_rate repricing_frequency prepayment_option collateral_type  \
0               12.44             Monthly                No         Secured
2               10.73           Quarterly                No       Unsecured
3               14.59         Half-Yearly                No       Unsecured
6               15.28         Half-Yearly                No         Secured
7               15.57         Half-Yearly               Yes         Secured
...               ...                 ...               ...             ...
799989          17.61         Half-Yearly                No       Unsecured
799990          12.03             Monthly                No         Secured
799995           8.46         Half-Yearly                No       Unsecured
799996          11.78           Quarterly               Yes         Secured
799999          16.26         Half-Yearly               Yes       Unsecured

         region  tenure_months  flag_high_interest  flag_invalid_amount  \
0       Central            144               False                False
2          East             51               False                 True
3          East             21               False                 True
6         North            178               False                False
7          East             73               False                 True
...         ...            ...                 ...                  ...
799989  Central            233               False                 True
799990    North            201               False                 True
799995    South            135               False                False
799996     East            139               False                False
799999     East            173               False                False

        flag_long_tenure  flag_missing  any_violation
0                   True         False           True
2                  False         False           True
3                  False         False           True
6                   True         False           True
7                  False         False           True
...                  ...           ...            ...
799989              True         False           True
799990              True         False           True
799995              True         False           True
799996              True         False           True
799999              True         False           True

[568450 rows x 15 columns]

In [76]:
print(violations.head())

   loan_id customer_segment  sanction_amount  outstanding_principal  \
0        1        Corporate          4473539                1399755
2        3        Corporate          2448830                3963945
3        4        Corporate          3136211                3933227
6        7        Corporate          3036670                2774929
7        8              SME          1535130                3332913

   interest_rate repricing_frequency prepayment_option collateral_type  \
0          12.44             Monthly                No         Secured
2          10.73           Quarterly                No       Unsecured
3          14.59         Half-Yearly                No       Unsecured
6          15.28         Half-Yearly                No         Secured
7          15.57         Half-Yearly               Yes         Secured

    region  tenure_months  flag_high_interest  flag_invalid_amount  \
0  Central            144               False                False
2     East             51               False                 True
3     East             21               False                 True
6    North            178               False                False
7     East             73               False                 True

   flag_long_tenure  flag_missing  any_violation
0              True         False           True
2             False         False           True
3             False         False           True
6              True         False           True
7             False         False           True

In [5]:
df_loan['data_quality_flag'] = (
    df_loan['flag_high_interest'] &
    ['flag_invalid_amount'] &
    ['flag_long_tenure'] &
    ['flag_missing'] )

NameError: name 'df_loan' is not defined

In [6]:
invalid_records = df_loan[df_loan['data_quality_flag'] == False]

NameError: name 'df_loan' is not defined

Reading Borrowing Fund Dataset

In [12]:
df_borr=pd.read_csv("C:/Users/admin/Downloads/datasets/borrowing_funding_dataset.csv")

In [13]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   borrowing_id         200000 non-null  int64
 1   funding_source       200000 non-null  str
 2   cost_of_funds        200000 non-null  float64
 3   maturity_bucket      200000 non-null  str
 4   interest_reset_type  200000 non-null  str
 5   borrowing_amount     200000 non-null  int64
 6   rollover_risk_score  200000 non-null  float64
dtypes: float64(2), int64(2), str(3)
memory usage: 10.7 MB

In [14]:
df_borr.shape

(200000, 7)

In [16]:
df_borr.columns

Index(['borrowing_id', 'funding_source', 'cost_of_funds', 'maturity_bucket',
       'interest_reset_type', 'borrowing_amount', 'rollover_risk_score'],
      dtype='str')

In [17]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   borrowing_id         200000 non-null  int64
 1   funding_source       200000 non-null  str
 2   cost_of_funds        200000 non-null  float64
 3   maturity_bucket      200000 non-null  str
 4   interest_reset_type  200000 non-null  str
 5   borrowing_amount     200000 non-null  int64
 6   rollover_risk_score  200000 non-null  float64
dtypes: float64(2), int64(2), str(3)
memory usage: 10.7 MB

In [18]:
df_borr.isnull().sum()

borrowing_id           0
funding_source         0
cost_of_funds          0
maturity_bucket        0
interest_reset_type    0
borrowing_amount       0
rollover_risk_score    0
dtype: int64

In [20]:
df_borr.drop_duplicates()

,borrowing_id,funding_source,cost_of_funds,maturity_bucket,interest_reset_type,borrowing_amount,rollover_risk_score
0,1,NCD,9.07,6M,Floating,8928717,0.9472
1,2,Term Loan,8.69,6M,Floating,31344155,0.2102
2,3,Bank Line,7.46,6M,Floating,21925818,0.3430
3,4,NCD,8.45,3Y,Floating,11737224,0.9142
4,5,NCD,7.56,3Y,Fixed,43446206,0.6087
...,...,...,...,...,...,...,...
199995,199996,Term Loan,5.65,3Y,Floating,18949628,0.6378
199996,199997,Bank Line,9.38,3M,Fixed,10606928,0.0016
199997,199998,Commercial Paper,9.39,3M,Fixed,33548319,0.5925
199998,199999,NCD,5.33,3M,Fixed,44607877,0.0913
199999,200000,Term Loan,9.93,3M,Floating,14007877,0.4326

In [21]:
df_borr.isnull().sum()

borrowing_id           0
funding_source         0
cost_of_funds          0
maturity_bucket        0
interest_reset_type    0
borrowing_amount       0
rollover_risk_score    0
dtype: int64

In [82]:
((df_borr.isnull().sum()/len(df_borr))*100)

borrowing_id           0.0
funding_source         0.0
cost_of_funds          0.0
maturity_bucket        0.0
interest_reset_type    0.0
borrowing_amount       0.0
rollover_risk_score    0.0
liability_flag         0.0
dtype: float64

In [22]:
invalid_cost = df_borr[(df_borr['cost_of_funds'] < 0) | (df_borr['cost_of_funds'] > 20)]

In [23]:
print(invalid_cost)

Empty DataFrame
Columns: [borrowing_id, funding_source, cost_of_funds, maturity_bucket, interest_reset_type, borrowing_amount, rollover_risk_score]
Index: []

In [28]:
df_borr['borrowing_id'].unique()

array([     1,      2,      3, ..., 199998, 199999, 200000],
      shape=(200000,))

In [29]:
invalid_risk = df_borr[(df_borr['rollover_risk_score'] < 0) | (df_borr['rollover_risk_score'] > 1)]

In [30]:
print("Invalid risk score count:", invalid_risk.shape[0])

Invalid risk score count: 0

In [31]:
print("Invalid risk score count")

Invalid risk score count

In [44]:
invalid_cost = df_borr[(df_borr['cost_of_funds'] < 0) | (df_borr['cost_of_funds'] > 20)]

In [46]:
print("invalid_cost")

invalid_cost

In [34]:
invalid_amount = df_borr[df_borr['borrowing_amount'] <= 0]

In [35]:
print("invalid_amount")

invalid_amount

In [55]:
df_borr['liability_flag'] =( 
    (df_borr['cost_of_funds'] >= 0) | (df_borr['cost_of_funds'] <= 20) |
    (df_borr['rollover_risk_score'] >= 0) | (df_borr['rollover_risk_score'] <= 1)|
    (df_borr['borrowing_amount'] > 0)
)

In [61]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   borrowing_id         200000 non-null  int64
 1   funding_source       200000 non-null  str
 2   cost_of_funds        200000 non-null  float64
 3   maturity_bucket      200000 non-null  str
 4   interest_reset_type  200000 non-null  str
 5   borrowing_amount     200000 non-null  int64
 6   rollover_risk_score  200000 non-null  float64
 7   liability_flag       200000 non-null  bool
dtypes: bool(1), float64(2), int64(2), str(3)
memory usage: 10.9 MB

0         True
1         True
2         True
3         True
4         True
          ...
199995    True
199996    True
199997    True
199998    True
199999    True
Name: cost_of_funds, Length: 200000, dtype: bool

daily cashflow dataset

In [68]:
import pandas as pd
df_cash = pd.read_csv("C:/Users/admin/Downloads/datasets/daily_cashflow_dataset.csv")

In [69]:
df_cash.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  str
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
dtypes: int64(3), str(3)
memory usage: 13.7 MB

In [70]:
df_cash.describe()

       expected_amount  actual_amount      variance
count     3.000000e+05   3.000000e+05  3.000000e+05
mean      2.502234e+06   2.508259e+06  6.024329e+03
std       1.439052e+06   1.439805e+06  2.035640e+06
min       1.000400e+04   1.000100e+04 -4.971602e+06
25%       1.253227e+06   1.262189e+06 -1.454054e+06
50%       2.502554e+06   2.514194e+06  5.525500e+03
75%       3.746451e+06   3.755466e+06  1.467227e+06
max       4.999994e+06   4.999944e+06  4.977697e+06

In [71]:
df_cash.shape

(300000, 6)

In [73]:
df_cash.columns

Index(['date', 'inflow_type', 'outflow_type', 'expected_amount',
       'actual_amount', 'variance'],
      dtype='str')

In [74]:
df_cash.dtypes

date                 str
inflow_type          str
outflow_type         str
expected_amount    int64
actual_amount      int64
variance           int64
dtype: object

In [78]:
df_cash.isnull().sum()

date               0
inflow_type        0
outflow_type       0
expected_amount    0
actual_amount      0
variance           0
dtype: int64

In [79]:
(df_cash.isnull().sum()/len(df_cash))*100

date               0.0
inflow_type        0.0
outflow_type       0.0
expected_amount    0.0
actual_amount      0.0
variance           0.0
dtype: float64

In [81]:
df_cash.duplicated().sum()

np.int64(0)

In [97]:
df_cash_expected = df_cash[df_cash['expected_amount'] >= 0]

In [102]:
print(df_cash_expected)

              date inflow_type         outflow_type  expected_amount  \
0       2023-07-09        Fees     Interest Payment          4174650
1       2022-01-10         EMI  Operational Expense          4130107
2       2024-09-30        Fees  Principal Repayment          1513713
3       2023-10-07        Fees  Operational Expense          4968504
4       2024-05-25        Fees     Interest Payment          2750623
...            ...         ...                  ...              ...
299995  2024-12-07         EMI     Interest Payment          4340893
299996  2023-01-05         EMI     Interest Payment          2387192
299997  2024-09-08         EMI     Interest Payment          2581758
299998  2022-07-08         EMI     Interest Payment          2083312
299999  2022-02-22        Fees  Operational Expense          2755196

        actual_amount  variance
0             3827391   -347259
1             4793421    663314
2             4631343   3117630
3             1084464  -3884040
4              811231  -1939392
...               ...       ...
299995        4176454   -164439
299996         149084  -2238108
299997        2363995   -217763
299998        4731013   2647701
299999         401665  -2353531

[300000 rows x 6 columns]

In [103]:
df_cash_actual=df_cash[df_cash["actual_amount"]>=0]

In [104]:
print(df_cash_actual)

              date inflow_type         outflow_type  expected_amount  \
0       2023-07-09        Fees     Interest Payment          4174650
1       2022-01-10         EMI  Operational Expense          4130107
2       2024-09-30        Fees  Principal Repayment          1513713
3       2023-10-07        Fees  Operational Expense          4968504
4       2024-05-25        Fees     Interest Payment          2750623
...            ...         ...                  ...              ...
299995  2024-12-07         EMI     Interest Payment          4340893
299996  2023-01-05         EMI     Interest Payment          2387192
299997  2024-09-08         EMI     Interest Payment          2581758
299998  2022-07-08         EMI     Interest Payment          2083312
299999  2022-02-22        Fees  Operational Expense          2755196

        actual_amount  variance
0             3827391   -347259
1             4793421    663314
2             4631343   3117630
3             1084464  -3884040
4              811231  -1939392
...               ...       ...
299995        4176454   -164439
299996         149084  -2238108
299997        2363995   -217763
299998        4731013   2647701
299999         401665  -2353531

[300000 rows x 6 columns]

In [105]:
df_cash.columns

Index(['date', 'inflow_type', 'outflow_type', 'expected_amount',
       'actual_amount', 'variance'],
      dtype='str')

In [112]:
df_cash['variance'] = df_cash['actual_amount'] - df_cash['expected_amount']

In [114]:
print(df_cash['variance'] )

0         -347259
1          663314
2         3117630
3        -3884040
4        -1939392
           ...
299995    -164439
299996   -2238108
299997    -217763
299998    2647701
299999   -2353531
Name: variance, Length: 300000, dtype: int64

In [119]:


df_cash['date_str_length'] = df_cash['date'].astype(str).str.len()

df_cash['date_str_length'].value_counts()

date_str_length
10    300000
Name: count, dtype: int64

In [121]:
df_cash.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  str
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
 6   date_str_length  300000 non-null  int64
dtypes: int64(4), str(3)
memory usage: 16.0 MB

In [122]:
Q1 = df_cash['variance'].quantile(0.25)
Q3 = df_cash['variance'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [130]:
print(df_cash["variance"])

0         -347259
1          663314
2         3117630
3        -3884040
4        -1939392
           ...
299995    -164439
299996   -2238108
299997    -217763
299998    2647701
299999   -2353531
Name: variance, Length: 300000, dtype: int64

In [125]:
variance_outliers = df_cash[
    (df_cash['variance'] < lower_bound) |
    (df_cash['variance'] > upper_bound)
]

variance_outliers

Empty DataFrame
Columns: [date, inflow_type, outflow_type, expected_amount, actual_amount, variance, date_str_length]
Index: []

In [128]:
df_cash[variance_outliers]

,date,inflow_type,outflow_type,expected_amount,actual_amount,variance,date_str_length
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
299995,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299996,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299997,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299998,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299999,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
 neg_expected = df_cash[df_cash['expected_amount'] > 0]

In [133]:
print(df_cash["variance"])

0         -347259
1          663314
2         3117630
3        -3884040
4        -1939392
           ...
299995    -164439
299996   -2238108
299997    -217763
299998    2647701
299999   -2353531
Name: variance, Length: 300000, dtype: int64

In [134]:
print(df_cash[neg_expected])

       date inflow_type outflow_type  expected_amount  actual_amount  \
0       NaN         NaN          NaN              NaN            NaN
1       NaN         NaN          NaN              NaN            NaN
2       NaN         NaN          NaN              NaN            NaN
3       NaN         NaN          NaN              NaN            NaN
4       NaN         NaN          NaN              NaN            NaN
...     ...         ...          ...              ...            ...
299995  NaN         NaN          NaN              NaN            NaN
299996  NaN         NaN          NaN              NaN            NaN
299997  NaN         NaN          NaN              NaN            NaN
299998  NaN         NaN          NaN              NaN            NaN
299999  NaN         NaN          NaN              NaN            NaN

        variance  date_str_length
0            NaN              NaN
1            NaN              NaN
2            NaN              NaN
3            NaN              NaN
4            NaN              NaN
...          ...              ...
299995       NaN              NaN
299996       NaN              NaN
299997       NaN              NaN
299998       NaN              NaN
299999       NaN              NaN

[300000 rows x 7 columns]

In [140]:
print(df_cash["variance"])

0         -347259
1          663314
2         3117630
3        -3884040
4        -1939392
           ...
299995    -164439
299996   -2238108
299997    -217763
299998    2647701
299999   -2353531
Name: variance, Length: 300000, dtype: int64

macro dataset validation

In [147]:
import pandas as pd
df_macro = pd.read_csv("C:/Users/admin/Downloads/datasets/market_macro_dataset.csv")

In [148]:
df_macro.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             600000 non-null  str
 1   repo_rate        600000 non-null  float64
 2   gsec_10y         600000 non-null  float64
 3   cp_rate          600000 non-null  float64
 4   inflation_cpi    600000 non-null  float64
 5   liquidity_index  600000 non-null  float64
 6   usd_inr          600000 non-null  float64
dtypes: float64(6), str(1)
memory usage: 32.0 MB

In [149]:
df_macro.describe()

,repo_rate,gsec_10y,cp_rate,inflation_cpi,liquidity_index,usd_inr
count,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000
mean,5.749853,6.999804,7.000133,5.500726,0.000235,80.005830
std,1.009055,0.865009,1.154134,1.443123,1.156002,5.775332
min,4.000000,5.500000,5.000000,3.000000,-2.000000,70.000000
25%,4.880000,6.250000,6.000000,4.250000,-1.003000,75.000000
50%,5.750000,7.000000,7.000000,5.500000,0.002000,80.000000
75%,6.620000,7.750000,8.000000,6.750000,1.003000,85.010000
max,7.500000,8.500000,9.000000,8.000000,2.000000,90.000000

In [151]:
df_macro.columns

Index(['date', 'repo_rate', 'gsec_10y', 'cp_rate', 'inflation_cpi',
       'liquidity_index', 'usd_inr'],
      dtype='str')

In [152]:
df_macro.shape

(600000, 7)

In [155]:
df_macro.dtypes

date                   str
repo_rate          float64
gsec_10y           float64
cp_rate            float64
inflation_cpi      float64
liquidity_index    float64
usd_inr            float64
dtype: object

In [157]:
df_macro.describe()

,repo_rate,gsec_10y,cp_rate,inflation_cpi,liquidity_index,usd_inr
count,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000
mean,5.749853,6.999804,7.000133,5.500726,0.000235,80.005830
std,1.009055,0.865009,1.154134,1.443123,1.156002,5.775332
min,4.000000,5.500000,5.000000,3.000000,-2.000000,70.000000
25%,4.880000,6.250000,6.000000,4.250000,-1.003000,75.000000
50%,5.750000,7.000000,7.000000,5.500000,0.002000,80.000000
75%,6.620000,7.750000,8.000000,6.750000,1.003000,85.010000
max,7.500000,8.500000,9.000000,8.000000,2.000000,90.000000

In [159]:
df_macro.isnull().sum()

date               0
repo_rate          0
gsec_10y           0
cp_rate            0
inflation_cpi      0
liquidity_index    0
usd_inr            0
dtype: int64

In [160]:
(df_macro.isnull().sum()/len(df_macro))*100

date               0.0
inflow_type        0.0
outflow_type       0.0
expected_amount    0.0
actual_amount      0.0
variance           0.0
date_str_length    0.0
dtype: float64

In [163]:
df_macro.duplicated().count()

np.int64(600000)

In [167]:
invalid_repo = (df_macro['repo_rate'] < 0) | (df_macro['repo_rate'] > 15)

In [169]:
df_macro[invalid_repo]

Empty DataFrame
Columns: [date, repo_rate, gsec_10y, cp_rate, inflation_cpi, liquidity_index, usd_inr]
Index: []

In [170]:
invalid_inflation = df_macro['inflation_cpi'] < 0

In [171]:
df_macro[invalid_inflation]

Empty DataFrame
Columns: [date, repo_rate, gsec_10y, cp_rate, inflation_cpi, liquidity_index, usd_inr]
Index: []

In [172]:
invalid_usd = (df_macro['usd_inr'] < 50) | (df_macro['usd_inr'] > 120)

In [174]:
df_macro[invalid_usd]

Empty DataFrame
Columns: [date, repo_rate, gsec_10y, cp_rate, inflation_cpi, liquidity_index, usd_inr]
Index: []

In [175]:
df_macro = df_macro.sort_values('date')

In [176]:
df_macro

,date,repo_rate,gsec_10y,cp_rate,inflation_cpi,liquidity_index,usd_inr
204336,2022-01-01,4.93,6.91,7.70,5.60,-1.314,72.09
452217,2022-01-01,4.40,8.10,6.66,3.37,1.394,82.09
256819,2022-01-01,6.44,6.65,7.59,5.32,-1.341,82.67
163733,2022-01-01,5.13,5.66,8.38,6.39,0.908,77.32
452289,2022-01-01,4.39,8.15,8.29,4.84,0.238,75.73
...,...,...,...,...,...,...,...
591662,2024-12-30,5.89,6.05,5.33,7.89,-1.265,80.00
318839,2024-12-30,7.44,6.21,6.92,3.20,1.746,77.71
563398,2024-12-30,5.25,6.84,6.12,7.48,-0.758,79.81
329990,2024-12-30,5.51,7.97,5.84,4.81,-1.977,77.76
185929,2024-12-30,6.36,7.86,8.69,4.20,-1.337,79.03

In [178]:
df_macro['date_diff'] = df_macro['date']

In [180]:
df_macro["date_diff"]

204336    2022-01-01
452217    2022-01-01
256819    2022-01-01
163733    2022-01-01
452289    2022-01-01
             ...
591662    2024-12-30
318839    2024-12-30
563398    2024-12-30
329990    2024-12-30
185929    2024-12-30
Name: date_diff, Length: 600000, dtype: str

In [191]:
duplicate_dates = df_macro[df_macro.duplicated(subset=['date'], keep=False)]

duplicate_dates

,date,repo_rate,gsec_10y,cp_rate,inflation_cpi,liquidity_index,usd_inr,date_diff
204336,2022-01-01,4.93,6.91,7.70,5.60,-1.314,72.09,2022-01-01
452217,2022-01-01,4.40,8.10,6.66,3.37,1.394,82.09,2022-01-01
256819,2022-01-01,6.44,6.65,7.59,5.32,-1.341,82.67,2022-01-01
163733,2022-01-01,5.13,5.66,8.38,6.39,0.908,77.32,2022-01-01
452289,2022-01-01,4.39,8.15,8.29,4.84,0.238,75.73,2022-01-01
...,...,...,...,...,...,...,...,...
591662,2024-12-30,5.89,6.05,5.33,7.89,-1.265,80.00,2024-12-30
318839,2024-12-30,7.44,6.21,6.92,3.20,1.746,77.71,2024-12-30
563398,2024-12-30,5.25,6.84,6.12,7.48,-0.758,79.81,2024-12-30
329990,2024-12-30,5.51,7.97,5.84,4.81,-1.977,77.76,2024-12-30
185929,2024-12-30,6.36,7.86,8.69,4.20,-1.337,79.03,2024-12-30

In [192]:
df_macro.info()

<class 'pandas.DataFrame'>
Index: 600000 entries, 204336 to 185929
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             600000 non-null  str
 1   repo_rate        600000 non-null  float64
 2   gsec_10y         600000 non-null  float64
 3   cp_rate          600000 non-null  float64
 4   inflation_cpi    600000 non-null  float64
 5   liquidity_index  600000 non-null  float64
 6   usd_inr          600000 non-null  float64
 7   date_diff        600000 non-null  str
dtypes: float64(6), str(2)
memory usage: 41.2 MB

-------------------------------------