phase 3-------
all datasets

In [4]:
import pandas as pd
df_loan=pd.read_csv("C:/Users/admin/Downloads/datasets/loan_portfolio_dataset.csv")
df_loan['outstanding_principal'] = pd.to_numeric(df_loan['outstanding_principal'])

In [5]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_id                800000 non-null  int64
 1   customer_segment       800000 non-null  str
 2   sanction_amount        800000 non-null  int64
 3   outstanding_principal  800000 non-null  int64
 4   interest_rate          800000 non-null  float64
 5   repricing_frequency    800000 non-null  str
 6   prepayment_option      800000 non-null  str
 7   collateral_type        800000 non-null  str
 8   region                 800000 non-null  str
 9   tenure_months          800000 non-null  int64
dtypes: float64(1), int64(4), str(5)
memory usage: 61.0 MB

In [6]:
df_loan.describe()

,loan_id,sanction_amount,outstanding_principal,interest_rate,tenure_months
count,800000.000000,8.000000e+05,8.000000e+05,800000.000000,800000.000000
mean,400000.500000,2.523013e+06,2.004313e+06,12.496878,125.485942
std,230940.252013,1.430761e+06,1.151454e+06,3.175649,65.827576
min,1.000000,5.000600e+04,1.002000e+04,7.000000,12.000000
25%,200000.750000,1.282186e+06,1.007734e+06,9.750000,68.000000
50%,400000.500000,2.520272e+06,2.003104e+06,12.500000,126.000000
75%,600000.250000,3.762831e+06,3.002133e+06,15.240000,182.000000
max,800000.000000,4.999998e+06,3.999995e+06,18.000000,239.000000

In [7]:
df_loan['outstanding_principal'] = pd.to_numeric(df_loan['outstanding_principal'])

In [8]:
df_loan['outstanding_principal']

0         1399755
1         1509414
2         3963945
3         3933227
4         1414890
           ...
799995    1827723
799996    3717405
799997    1035235
799998     572950
799999    1629175
Name: outstanding_principal, Length: 800000, dtype: int64

In [9]:
df_loan['interest_rate'] = pd.to_numeric(df_loan['interest_rate'])

In [10]:
df_loan['interest_rate']

0         12.44
1          8.52
2         10.73
3         14.59
4          7.56
          ...
799995     8.46
799996    11.78
799997     7.23
799998     8.15
799999    16.26
Name: interest_rate, Length: 800000, dtype: float64

In [11]:
df_loan['monthly_interest_income'] = (
    df_loan['outstanding_principal'] * df_loan['interest_rate']
) / 12

In [12]:
df_loan['monthly_interest_income']

0         1.451079e+06
1         1.071684e+06
2         3.544427e+06
3         4.782148e+06
4         8.913807e+05
              ...
799995    1.288545e+06
799996    3.649253e+06
799997    6.237291e+05
799998    3.891285e+05
799999    2.207532e+06
Name: monthly_interest_income, Length: 800000, dtype: float64

In [13]:
df_loan['tenure_months'] = pd.to_numeric(df_loan['tenure_months'])

In [14]:
df_loan['tenure_months']

0         144
1          18
2          51
3          21
4          91
         ...
799995    135
799996    139
799997     15
799998    109
799999    173
Name: tenure_months, Length: 800000, dtype: int64

In [19]:
import numpy as np

conditions = [
    (df_loan['tenure_months'] >= 0) & (df_loan['tenure_months'] <= 1),
    (df_loan['tenure_months'] > 1) & (df_loan['tenure_months'] <= 3),
    (df_loan['tenure_months'] > 3) & (df_loan['tenure_months'] <= 6),
    (df_loan['tenure_months'] > 6) & (df_loan['tenure_months'] <= 12),
    (df_loan['tenure_months'] > 12)
]

choices = [
    '0-30 Days',
    '30-90 Days',
    '90-180 Days',
    '6M-1Y',
    '1Y+'
]
df_loan['alm_bucket'] = np.select(conditions, choices, default='unknown')

In [20]:
df_loan['alm_bucket']

0         1Y+
1         1Y+
2         1Y+
3         1Y+
4         1Y+
         ...
799995    1Y+
799996    1Y+
799997    1Y+
799998    1Y+
799999    1Y+
Name: alm_bucket, Length: 800000, dtype: str

In [21]:
df_loan['is_floating'] = df_loan['repricing_frequency'] != 'Fixed'

In [22]:
df_loan['is_floating']

0         True
1         True
2         True
3         True
4         True
          ...
799995    True
799996    True
799997    True
799998    True
799999    True
Name: is_floating, Length: 800000, dtype: bool

In [25]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 13 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   loan_id                  800000 non-null  int64
 1   customer_segment         800000 non-null  str
 2   sanction_amount          800000 non-null  int64
 3   outstanding_principal    800000 non-null  int64
 4   interest_rate            800000 non-null  float64
 5   repricing_frequency      800000 non-null  str
 6   prepayment_option        800000 non-null  str
 7   collateral_type          800000 non-null  str
 8   region                   800000 non-null  str
 9   tenure_months            800000 non-null  int64
 10  monthly_interest_income  800000 non-null  float64
 11  alm_bucket               800000 non-null  str
 12  is_floating              800000 non-null  bool
dtypes: bool(1), float64(2), int64(4), str(6)
memory usage: 74.0 MB

borr---------------

In [26]:
import pandas as pd
df_borr = pd.read_csv("C:/Users/admin/Downloads/datasets/borrowing_funding_dataset.csv")

In [27]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   borrowing_id         200000 non-null  int64
 1   funding_source       200000 non-null  str
 2   cost_of_funds        200000 non-null  float64
 3   maturity_bucket      200000 non-null  str
 4   interest_reset_type  200000 non-null  str
 5   borrowing_amount     200000 non-null  int64
 6   rollover_risk_score  200000 non-null  float64
dtypes: float64(2), int64(2), str(3)
memory usage: 10.7 MB

In [29]:
df_borr['annual_interest_expense'] = (
    df_borr['borrowing_amount'] * df_borr['cost_of_funds']
)

In [30]:
df_borr['annual_interest_expense']

0         8.098346e+07
1         2.723807e+08
2         1.635666e+08
3         9.917954e+07
4         3.284533e+08
              ...
199995    1.070654e+08
199996    9.949298e+07
199997    3.150187e+08
199998    2.377600e+08
199999    1.390982e+08
Name: annual_interest_expense, Length: 200000, dtype: float64

In [31]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   borrowing_id             200000 non-null  int64
 1   funding_source           200000 non-null  str
 2   cost_of_funds            200000 non-null  float64
 3   maturity_bucket          200000 non-null  str
 4   interest_reset_type      200000 non-null  str
 5   borrowing_amount         200000 non-null  int64
 6   rollover_risk_score      200000 non-null  float64
 7   annual_interest_expense  200000 non-null  float64
dtypes: float64(3), int64(2), str(3)
memory usage: 12.2 MB

In [32]:
df_borr['short_term_flag'] = df_borr['maturity_bucket'].isin(['1M', '3M'])

In [33]:
df_borr['short_term_flag']

0         False
1         False
2         False
3         False
4         False
          ...
199995    False
199996     True
199997     True
199998     True
199999     True
Name: short_term_flag, Length: 200000, dtype: bool

In [34]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   borrowing_id             200000 non-null  int64
 1   funding_source           200000 non-null  str
 2   cost_of_funds            200000 non-null  float64
 3   maturity_bucket          200000 non-null  str
 4   interest_reset_type      200000 non-null  str
 5   borrowing_amount         200000 non-null  int64
 6   rollover_risk_score      200000 non-null  float64
 7   annual_interest_expense  200000 non-null  float64
 8   short_term_flag          200000 non-null  bool
dtypes: bool(1), float64(3), int64(2), str(3)
memory usage: 12.4 MB

In [38]:
df_borr["funding_risk_exposure"] = (
    df_borr["borrowing_amount"] * df_borr["rollover_risk_score"]
)

In [39]:
df_borr["funding_risk_exposure"]

0         8.457281e+06
1         6.588541e+06
2         7.520556e+06
3         1.073017e+07
4         2.644571e+07
              ...
199995    1.208607e+07
199996    1.697108e+04
199997    1.987738e+07
199998    4.072699e+06
199999    6.059808e+06
Name: funding_risk_exposure, Length: 200000, dtype: float64

In [40]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   borrowing_id             200000 non-null  int64
 1   funding_source           200000 non-null  str
 2   cost_of_funds            200000 non-null  float64
 3   maturity_bucket          200000 non-null  str
 4   interest_reset_type      200000 non-null  str
 5   borrowing_amount         200000 non-null  int64
 6   rollover_risk_score      200000 non-null  float64
 7   annual_interest_expense  200000 non-null  float64
 8   short_term_flag          200000 non-null  bool
 9   funding_risk_exposure    200000 non-null  float64
dtypes: bool(1), float64(4), int64(2), str(3)
memory usage: 13.9 MB

cashflow------------

In [42]:
import pandas as pd
df_cash = pd.read_csv("C:/Users/admin/Downloads/datasets/daily_cashflow_dataset.csv")

In [43]:
df_cash.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  str
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
dtypes: int64(3), str(3)
memory usage: 13.7 MB

In [44]:
df_cash.describe()

       expected_amount  actual_amount      variance
count     3.000000e+05   3.000000e+05  3.000000e+05
mean      2.502234e+06   2.508259e+06  6.024329e+03
std       1.439052e+06   1.439805e+06  2.035640e+06
min       1.000400e+04   1.000100e+04 -4.971602e+06
25%       1.253227e+06   1.262189e+06 -1.454054e+06
50%       2.502554e+06   2.514194e+06  5.525500e+03
75%       3.746451e+06   3.755466e+06  1.467227e+06
max       4.999994e+06   4.999944e+06  4.977697e+06

In [46]:
df_cash['cashflow_date'] = pd.to_datetime(df_cash['date'])

df_cash = df_cash.sort_values(by='date')

In [47]:
df_cash['cashflow_date']

204195   2022-01-01
270483   2022-01-01
202953   2022-01-01
202689   2022-01-01
245882   2022-01-01
            ...
287550   2024-12-30
5317     2024-12-30
245295   2024-12-30
216544   2024-12-30
163397   2024-12-30
Name: cashflow_date, Length: 300000, dtype: datetime64[us]

In [62]:
import pandas as pd
df_cash['net_cashflow'] = (
    df_cash['expected_amount'] - df_cash['actual_amount'])

In [63]:
df_cash['net_cashflow']

204195   -2220341
270483   -1449739
202953   -1498403
202689    4000110
245882     169995
           ...
287550      19647
5317       851913
245295    4166920
216544    -279734
163397    3252442
Name: net_cashflow, Length: 300000, dtype: int64

In [64]:
df_cash.info()

<class 'pandas.DataFrame'>
Index: 300000 entries, 204195 to 163397
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  str
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
 6   cashflow_date    300000 non-null  datetime64[us]
 7   net_cashflow     300000 non-null  int64
dtypes: datetime64[us](1), int64(4), str(3)
memory usage: 20.6 MB

In [65]:
df_cash['month'] = df_cash['cashflow_date'].dt.month

In [66]:
df_cash['month']

204195     1
270483     1
202953     1
202689     1
245882     1
          ..
287550    12
5317      12
245295    12
216544    12
163397    12
Name: month, Length: 300000, dtype: int32

In [67]:
df_cash['quarter'] = df_cash['cashflow_date'].dt.quarter

In [68]:
df_cash['quarter']

204195    1
270483    1
202953    1
202689    1
245882    1
         ..
287550    4
5317      4
245295    4
216544    4
163397    4
Name: quarter, Length: 300000, dtype: int32

In [69]:
df_cash['financial_year'] = df_cash['cashflow_date'].dt.year

In [70]:
df_cash['financial_year']

204195    2022
270483    2022
202953    2022
202689    2022
245882    2022
          ...
287550    2024
5317      2024
245295    2024
216544    2024
163397    2024
Name: financial_year, Length: 300000, dtype: int32

In [71]:
df_cash['week_number'] = df_cash['cashflow_date'].dt.isocalendar().week

In [72]:
df_cash['week_number']

204195    52
270483    52
202953    52
202689    52
245882    52
          ..
287550     1
5317       1
245295     1
216544     1
163397     1
Name: week_number, Length: 300000, dtype: UInt32

In [73]:
df_cash[['cashflow_date', 'month', 'quarter', 'financial_year', 'week_number']].head()

       cashflow_date  month  quarter  financial_year  week_number
204195    2022-01-01      1        1            2022           52
270483    2022-01-01      1        1            2022           52
202953    2022-01-01      1        1            2022           52
202689    2022-01-01      1        1            2022           52
245882    2022-01-01      1        1            2022           52

In [74]:
df_cash[['cashflow_date', 'month', 'quarter', 'financial_year', 'week_number']]

       cashflow_date  month  quarter  financial_year  week_number
204195    2022-01-01      1        1            2022           52
270483    2022-01-01      1        1            2022           52
202953    2022-01-01      1        1            2022           52
202689    2022-01-01      1        1            2022           52
245882    2022-01-01      1        1            2022           52
...              ...    ...      ...             ...          ...
287550    2024-12-30     12        4            2024            1
5317      2024-12-30     12        4            2024            1
245295    2024-12-30     12        4            2024            1
216544    2024-12-30     12        4            2024            1
163397    2024-12-30     12        4            2024            1

[300000 rows x 5 columns]

In [75]:
df_cash.info()

<class 'pandas.DataFrame'>
Index: 300000 entries, 204195 to 163397
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  str
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
 6   cashflow_date    300000 non-null  datetime64[us]
 7   net_cashflow     300000 non-null  int64
 8   month            300000 non-null  int32
 9   quarter          300000 non-null  int32
 10  financial_year   300000 non-null  int32
 11  week_number      300000 non-null  UInt32
dtypes: UInt32(1), datetime64[us](1), int32(3), int64(4), str(3)
memory usage: 25.5 MB

macro-----------------

In [76]:
import pandas as pd
df_macro = pd.read_csv("C:/Users/admin/Downloads/datasets/market_macro_dataset.csv")

In [77]:
df_macro.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             600000 non-null  str
 1   repo_rate        600000 non-null  float64
 2   gsec_10y         600000 non-null  float64
 3   cp_rate          600000 non-null  float64
 4   inflation_cpi    600000 non-null  float64
 5   liquidity_index  600000 non-null  float64
 6   usd_inr          600000 non-null  float64
dtypes: float64(6), str(1)
memory usage: 32.0 MB

In [78]:
df_macro['date'] = pd.to_datetime(df_macro['date'])

df_macro = df_macro.sort_values(by='date')

In [79]:
df_macro['date']

204336   2022-01-01
452217   2022-01-01
256819   2022-01-01
163733   2022-01-01
452289   2022-01-01
            ...
591662   2024-12-30
318839   2024-12-30
563398   2024-12-30
329990   2024-12-30
185929   2024-12-30
Name: date, Length: 600000, dtype: datetime64[us]

In [83]:
df_macro['repo_rate'] = pd.to_numeric(df_macro['repo_rate'])

df_macro['repo_rate_change'] = df_macro['repo_rate']

In [84]:
df_macro['repo_rate_change']

204336    4.93
452217    4.40
256819    6.44
163733    5.13
452289    4.39
          ...
591662    5.89
318839    7.44
563398    5.25
329990    5.51
185929    6.36
Name: repo_rate_change, Length: 600000, dtype: float64

In [85]:
df_macro.info()

<class 'pandas.DataFrame'>
Index: 600000 entries, 204336 to 185929
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   date              600000 non-null  datetime64[us]
 1   repo_rate         600000 non-null  float64
 2   gsec_10y          600000 non-null  float64
 3   cp_rate           600000 non-null  float64
 4   inflation_cpi     600000 non-null  float64
 5   liquidity_index   600000 non-null  float64
 6   usd_inr           600000 non-null  float64
 7   repo_rate_change  600000 non-null  float64
dtypes: datetime64[us](1), float64(7)
memory usage: 41.2 MB

In [86]:
df_macro['cp_rate'] = pd.to_numeric(df_macro['cp_rate'])

In [87]:
df_macro['cp_rate']

204336    7.70
452217    6.66
256819    7.59
163733    8.38
452289    8.29
          ...
591662    5.33
318839    6.92
563398    6.12
329990    5.84
185929    8.69
Name: cp_rate, Length: 600000, dtype: float64

In [89]:
df_macro['market_stress_flag'] = (
    (df_macro['repo_rate_change'] > 50) |
    (df_macro['cp_rate'].pct_change() > 0.05)
)

In [90]:
df_macro['market_stress_flag']

204336    False
452217    False
256819     True
163733     True
452289    False
          ...
591662    False
318839     True
563398    False
329990    False
185929     True
Name: market_stress_flag, Length: 600000, dtype: bool

In [91]:
df_macro.info()

<class 'pandas.DataFrame'>
Index: 600000 entries, 204336 to 185929
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   date                600000 non-null  datetime64[us]
 1   repo_rate           600000 non-null  float64
 2   gsec_10y            600000 non-null  float64
 3   cp_rate             600000 non-null  float64
 4   inflation_cpi       600000 non-null  float64
 5   liquidity_index     600000 non-null  float64
 6   usd_inr             600000 non-null  float64
 7   repo_rate_change    600000 non-null  float64
 8   market_stress_flag  600000 non-null  bool
dtypes: bool(1), datetime64[us](1), float64(7)
memory usage: 41.8 MB

In [ ]:
----------------------------------