phase 4 for all data set-----------------

In [1]:
import pandas as pd
df_loan = pd.read_csv("C:/Users/admin/Downloads/datasets/loan_portfolio_dataset.csv")
df_borr = pd.read_csv("C:/Users/admin/Downloads/datasets/borrowing_funding_dataset.csv")
df_cash = pd.read_csv("C:/Users/admin/Downloads/datasets/daily_cashflow_dataset.csv") 
df_macro = pd.read_csv("C:/Users/admin/Downloads/datasets/market_macro_dataset")

In [2]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_id                800000 non-null  int64
 1   customer_segment       800000 non-null  str
 2   sanction_amount        800000 non-null  int64
 3   outstanding_principal  800000 non-null  int64
 4   interest_rate          800000 non-null  float64
 5   repricing_frequency    800000 non-null  str
 6   prepayment_option      800000 non-null  str
 7   collateral_type        800000 non-null  str
 8   region                 800000 non-null  str
 9   tenure_months          800000 non-null  int64
dtypes: float64(1), int64(4), str(5)
memory usage: 61.0 MB

In [4]:
import pandas as pd
df_borr = pd.read_csv("C:/Users/admin/Downloads/datasets/borrowing_funding_dataset.csv")

In [5]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   borrowing_id         200000 non-null  int64
 1   funding_source       200000 non-null  str
 2   cost_of_funds        200000 non-null  float64
 3   maturity_bucket      200000 non-null  str
 4   interest_reset_type  200000 non-null  str
 5   borrowing_amount     200000 non-null  int64
 6   rollover_risk_score  200000 non-null  float64
dtypes: float64(2), int64(2), str(3)
memory usage: 10.7 MB

In [6]:
import pandas as pd
df_cash = pd.read_csv("C:/Users/admin/Downloads/datasets/daily_cashflow_dataset.csv")

In [7]:
df_cash.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  str
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
dtypes: int64(3), str(3)
memory usage: 13.7 MB

In [9]:
import pandas as pd
df_macro = pd.read_csv("C:/Users/admin/Downloads/datasets/market_macro_dataset.csv")

In [10]:
df_macro.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             600000 non-null  str
 1   repo_rate        600000 non-null  float64
 2   gsec_10y         600000 non-null  float64
 3   cp_rate          600000 non-null  float64
 4   inflation_cpi    600000 non-null  float64
 5   liquidity_index  600000 non-null  float64
 6   usd_inr          600000 non-null  float64
dtypes: float64(6), str(1)
memory usage: 32.0 MB

In [12]:
import pandas as pd
df_cash['date'] = pd.to_datetime(df_cash['date'])

In [13]:
df_cash['date']

0        2023-07-09
1        2022-01-10
2        2024-09-30
3        2023-10-07
4        2024-05-25
            ...
299995   2024-12-07
299996   2023-01-05
299997   2024-09-08
299998   2022-07-08
299999   2022-02-22
Name: date, Length: 300000, dtype: datetime64[us]

In [17]:
import numpy as np

conditions = [
    (df_loan['tenure_months'] >= 0) & (df_loan['tenure_months'] <= 1),
    (df_loan['tenure_months'] > 1) & (df_loan['tenure_months'] <= 3),
    (df_loan['tenure_months'] > 3) & (df_loan['tenure_months'] <= 6),
    (df_loan['tenure_months'] > 6) & (df_loan['tenure_months'] <= 12),
    (df_loan['tenure_months'] > 12)
]

choices = [
    '0-30 Days',
    '30-90 Days',
    '90-180 Days',
    '6M-1Y',
    '1Y+'
]
df_loan['alm_bucket'] = np.select(conditions, choices, default='unknown')

In [18]:
df_loan['alm_bucket']

0         1Y+
1         1Y+
2         1Y+
3         1Y+
4         1Y+
         ...
799995    1Y+
799996    1Y+
799997    1Y+
799998    1Y+
799999    1Y+
Name: alm_bucket, Length: 800000, dtype: str

In [19]:
df_loan['alm_bucket'] = df_loan['alm_bucket'].str.lower().str.strip()

In [20]:
df_loan['alm_bucket']

0         1y+
1         1y+
2         1y+
3         1y+
4         1y+
         ...
799995    1y+
799996    1y+
799997    1y+
799998    1y+
799999    1y+
Name: alm_bucket, Length: 800000, dtype: str

In [22]:
import pandas as pd
df_cash['segment']= pd.cut(df_cash['variance'],bins=[0,100000,500000,float('inf')],labels=['low','medium','high'])

In [23]:
df_cash['segment']

0          NaN
1         high
2         high
3          NaN
4          NaN
          ...
299995     NaN
299996     NaN
299997     NaN
299998    high
299999     NaN
Name: segment, Length: 300000, dtype: category
Categories (3, str): ['low' < 'medium' < 'high']

In [24]:
df_cash['segment'] = df_cash['segment'].str.lower().str.strip()

In [25]:
df_cash['segment']

0          NaN
1         high
2         high
3          NaN
4          NaN
          ...
299995     NaN
299996     NaN
299997     NaN
299998    high
299999     NaN
Name: segment, Length: 300000, dtype: object

In [26]:
df_cash.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  datetime64[us]
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
 6   segment          150338 non-null  object
dtypes: datetime64[us](1), int64(3), object(1), str(2)
memory usage: 16.0+ MB

In [28]:
df_cash['date'] = pd.to_datetime(df_cash['date'])
df_loan['alm_bucket'] = df_loan['alm_bucket'].str.lower().str.strip()
df_cash['segment'] = df_cash['segment'].str.lower().str.strip()

In [115]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 13 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   loan_id                  800000 non-null  int64
 1   customer_segment         800000 non-null  str
 2   sanction_amount          800000 non-null  int64
 3   outstanding_principal    800000 non-null  int64
 4   interest_rate            800000 non-null  float64
 5   repricing_frequency      800000 non-null  str
 6   prepayment_option        800000 non-null  str
 7   collateral_type          800000 non-null  str
 8   region                   800000 non-null  str
 9   tenure_months            800000 non-null  int64
 10  alm_bucket               800000 non-null  str
 11  monthly_interest_income  800000 non-null  float64
 12  total_loan_inflow        800000 non-null  float64
dtypes: float64(3), int64(4), str(6)
memory usage: 79.3 MB

In [116]:
loan_agg = df_loan.groupby(
    ['alm_bucket', 'customer_segment'],)

In [117]:
loan_agg

In [36]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   borrowing_id         200000 non-null  int64
 1   funding_source       200000 non-null  str
 2   cost_of_funds        200000 non-null  float64
 3   maturity_bucket      200000 non-null  str
 4   interest_reset_type  200000 non-null  str
 5   borrowing_amount     200000 non-null  int64
 6   rollover_risk_score  200000 non-null  float64
dtypes: float64(2), int64(2), str(3)
memory usage: 10.7 MB

In [37]:
df_borr['maturity_bucket'] = df_borr['maturity_bucket'].str.lower().str.strip()

In [38]:
df_borr['maturity_bucket']

0         6m
1         6m
2         6m
3         3y
4         3y
          ..
199995    3y
199996    3m
199997    3m
199998    3m
199999    3m
Name: maturity_bucket, Length: 200000, dtype: str

In [39]:
df_borr['funding_source'] = df_borr['funding_source'].str.lower().str.strip()

In [40]:
df_borr['funding_source']

0                      ncd
1                term loan
2                bank line
3                      ncd
4                      ncd
                ...
199995           term loan
199996           bank line
199997    commercial paper
199998                 ncd
199999           term loan
Name: funding_source, Length: 200000, dtype: str

In [41]:
borr_agg_outflows = df_borr.groupby(
    ['maturity_bucket', 'funding_source'],
    as_index=False
)['borrowing_amount'].sum()

In [42]:
borr_agg_outflows

   maturity_bucket    funding_source  borrowing_amount
0               1m         bank line      252155061182
1               1m  commercial paper      256906388511
2               1m               ncd      256609690696
3               1m         term loan      253098710992
4               1y         bank line      259985637286
5               1y  commercial paper      256629353935
6               1y               ncd      248518245745
7               1y         term loan      258433697693
8               3m         bank line      256808126811
9               3m  commercial paper      253263150074
10              3m               ncd      253509606379
11              3m         term loan      254700757149
12              3y         bank line      257581150780
13              3y  commercial paper      251150319750
14              3y               ncd      251705390622
15              3y         term loan      255971638094
16              6m         bank line      253621103164
17              6m  commercial paper      254316713633
18              6m               ncd      256386903900
19              6m         term loan      252408882298

In [43]:
df_cash.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  datetime64[us]
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
 6   segment          150338 non-null  object
dtypes: datetime64[us](1), int64(3), object(1), str(2)
memory usage: 16.0+ MB

In [44]:
df_macro.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             600000 non-null  str
 1   repo_rate        600000 non-null  float64
 2   gsec_10y         600000 non-null  float64
 3   cp_rate          600000 non-null  float64
 4   inflation_cpi    600000 non-null  float64
 5   liquidity_index  600000 non-null  float64
 6   usd_inr          600000 non-null  float64
dtypes: float64(6), str(1)
memory usage: 32.0 MB

In [49]:
df_cash['date'] = pd.to_datetime(df_cash['date'])

In [50]:
df_cash['date']

0        2023-07-09
1        2022-01-10
2        2024-09-30
3        2023-10-07
4        2024-05-25
            ...
299995   2024-12-07
299996   2023-01-05
299997   2024-09-08
299998   2022-07-08
299999   2022-02-22
Name: date, Length: 300000, dtype: datetime64[us]

In [51]:
df_macro['date'] = pd.to_datetime(df_macro['date'])

In [52]:
df_macro['date']

0        2023-05-04
1        2024-09-16
2        2024-08-14
3        2024-04-23
4        2024-02-10
            ...
599995   2022-01-30
599996   2023-12-08
599997   2024-09-13
599998   2023-05-24
599999   2023-03-25
Name: date, Length: 600000, dtype: datetime64[us]

In [58]:
import pandas as pd
df_merged = pd.merge(
    df_cash,
    df_macro,
   left_on='date',right_on='date',
    how='inner')

In [59]:
df_merged

,date,inflow_type,outflow_type,expected_amount,actual_amount,variance,segment,repo_rate,gsec_10y,cp_rate,inflation_cpi,liquidity_index,usd_inr
0,2023-07-09,Fees,Interest Payment,4174650,3827391,-347259,NaN,5.25,6.25,7.79,6.26,1.126,76.64
1,2023-07-09,Fees,Interest Payment,4174650,3827391,-347259,NaN,7.03,5.67,7.01,7.27,-1.821,70.33
2,2023-07-09,Fees,Interest Payment,4174650,3827391,-347259,NaN,7.41,7.48,7.27,5.89,-0.462,83.61
3,2023-07-09,Fees,Interest Payment,4174650,3827391,-347259,NaN,4.98,7.52,8.08,4.08,0.921,71.84
4,2023-07-09,Fees,Interest Payment,4174650,3827391,-347259,NaN,5.78,6.89,8.19,7.96,1.949,73.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...
164397912,2022-02-22,Fees,Operational Expense,2755196,401665,-2353531,NaN,4.47,6.46,8.75,7.42,0.455,85.10
164397913,2022-02-22,Fees,Operational Expense,2755196,401665,-2353531,NaN,4.42,5.93,8.17,3.25,0.446,84.96
164397914,2022-02-22,Fees,Operational Expense,2755196,401665,-2353531,NaN,5.55,7.94,8.89,3.74,1.815,79.57
164397915,2022-02-22,Fees,Operational Expense,2755196,401665,-2353531,NaN,4.52,6.28,8.14,3.62,-0.182,82.03
164397916,2022-02-22,Fees,Operational Expense,2755196,401665,-2353531,NaN,4.55,7.46,6.52,6.76,-0.339,84.00

In [61]:
df_loan.info()
df_loan['monthly_interest_income'] = (
    df_loan['outstanding_principal'] * df_loan['interest_rate']
) / 12

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_id                800000 non-null  int64
 1   customer_segment       800000 non-null  str
 2   sanction_amount        800000 non-null  int64
 3   outstanding_principal  800000 non-null  int64
 4   interest_rate          800000 non-null  float64
 5   repricing_frequency    800000 non-null  str
 6   prepayment_option      800000 non-null  str
 7   collateral_type        800000 non-null  str
 8   region                 800000 non-null  str
 9   tenure_months          800000 non-null  int64
 10  alm_bucket             800000 non-null  str
dtypes: float64(1), int64(4), str(6)
memory usage: 67.1 MB

In [127]:
df_cash.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  datetime64[us]
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
 6   segment          150338 non-null  object
dtypes: datetime64[us](1), int64(3), object(1), str(2)
memory usage: 16.0+ MB

In [128]:
df_cash['date']

0        2023-07-09
1        2022-01-10
2        2024-09-30
3        2023-10-07
4        2024-05-25
            ...
299995   2024-12-07
299996   2023-01-05
299997   2024-09-08
299998   2022-07-08
299999   2022-02-22
Name: date, Length: 300000, dtype: datetime64[us]

In [63]:
df_loan['total_loan_inflow'] = (
    df_loan['outstanding_principal'] * df_loan['interest_rate']
) / 12

In [64]:
df_loan['total_loan_inflow']

0         1.451079e+06
1         1.071684e+06
2         3.544427e+06
3         4.782148e+06
4         8.913807e+05
              ...
799995    1.288545e+06
799996    3.649253e+06
799997    6.237291e+05
799998    3.891285e+05
799999    2.207532e+06
Name: total_loan_inflow, Length: 800000, dtype: float64

In [65]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 13 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   loan_id                  800000 non-null  int64
 1   customer_segment         800000 non-null  str
 2   sanction_amount          800000 non-null  int64
 3   outstanding_principal    800000 non-null  int64
 4   interest_rate            800000 non-null  float64
 5   repricing_frequency      800000 non-null  str
 6   prepayment_option        800000 non-null  str
 7   collateral_type          800000 non-null  str
 8   region                   800000 non-null  str
 9   tenure_months            800000 non-null  int64
 10  alm_bucket               800000 non-null  str
 11  monthly_interest_income  800000 non-null  float64
 12  total_loan_inflow        800000 non-null  float64
dtypes: float64(3), int64(4), str(6)
memory usage: 79.3 MB

In [89]:
import pandas as pd
df_borr= pd.read_csv("C:/Users/admin/Downloads/datasets/borrowing_funding_dataset.csv")

In [90]:
df_borr

,borrowing_id,funding_source,cost_of_funds,maturity_bucket,interest_reset_type,borrowing_amount,rollover_risk_score
0,1,NCD,9.07,6M,Floating,8928717,0.9472
1,2,Term Loan,8.69,6M,Floating,31344155,0.2102
2,3,Bank Line,7.46,6M,Floating,21925818,0.3430
3,4,NCD,8.45,3Y,Floating,11737224,0.9142
4,5,NCD,7.56,3Y,Fixed,43446206,0.6087
...,...,...,...,...,...,...,...
199995,199996,Term Loan,5.65,3Y,Floating,18949628,0.6378
199996,199997,Bank Line,9.38,3M,Fixed,10606928,0.0016
199997,199998,Commercial Paper,9.39,3M,Fixed,33548319,0.5925
199998,199999,NCD,5.33,3M,Fixed,44607877,0.0913
199999,200000,Term Loan,9.93,3M,Floating,14007877,0.4326

In [91]:
df_borr['total_borrowing_amount']=df_borr['borrowing_amount'].sum()

In [92]:
df_borr['total_borrowing_amount']

0         5093760528694
1         5093760528694
2         5093760528694
3         5093760528694
4         5093760528694
              ...
199995    5093760528694
199996    5093760528694
199997    5093760528694
199998    5093760528694
199999    5093760528694
Name: total_borrowing_amount, Length: 200000, dtype: int64

In [93]:
df_borr

,borrowing_id,funding_source,cost_of_funds,maturity_bucket,interest_reset_type,borrowing_amount,rollover_risk_score,total_borrowing_amount
0,1,NCD,9.07,6M,Floating,8928717,0.9472,5093760528694
1,2,Term Loan,8.69,6M,Floating,31344155,0.2102,5093760528694
2,3,Bank Line,7.46,6M,Floating,21925818,0.3430,5093760528694
3,4,NCD,8.45,3Y,Floating,11737224,0.9142,5093760528694
4,5,NCD,7.56,3Y,Fixed,43446206,0.6087,5093760528694
...,...,...,...,...,...,...,...,...
199995,199996,Term Loan,5.65,3Y,Floating,18949628,0.6378,5093760528694
199996,199997,Bank Line,9.38,3M,Fixed,10606928,0.0016,5093760528694
199997,199998,Commercial Paper,9.39,3M,Fixed,33548319,0.5925,5093760528694
199998,199999,NCD,5.33,3M,Fixed,44607877,0.0913,5093760528694
199999,200000,Term Loan,9.93,3M,Floating,14007877,0.4326,5093760528694

In [97]:
df_loan['total_loan_inflow'] = pd.to_numeric(df_loan['total_loan_inflow'])

In [98]:
df_loan['total_loan_inflow']

0         1.451079e+06
1         1.071684e+06
2         3.544427e+06
3         4.782148e+06
4         8.913807e+05
              ...
799995    1.288545e+06
799996    3.649253e+06
799997    6.237291e+05
799998    3.891285e+05
799999    2.207532e+06
Name: total_loan_inflow, Length: 800000, dtype: float64

In [100]:
df_borr['total_borrowing_amount'] = pd.to_numeric(df_borr['total_borrowing_amount'])

In [101]:
df_borr['total_borrowing_amount']

0         5093760528694
1         5093760528694
2         5093760528694
3         5093760528694
4         5093760528694
              ...
199995    5093760528694
199996    5093760528694
199997    5093760528694
199998    5093760528694
199999    5093760528694
Name: total_borrowing_amount, Length: 200000, dtype: int64

In [130]:
df_Net_Liquidity_Position =  (df_loan['total_loan_inflow'] - df_borr['total_borrowing_amount'])

In [131]:
df_Net_Liquidity_Position

0        -5.093759e+12
1        -5.093759e+12
2        -5.093757e+12
3        -5.093756e+12
4        -5.093760e+12
              ...
799995             NaN
799996             NaN
799997             NaN
799998             NaN
799999             NaN
Length: 800000, dtype: float64

In [129]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 13 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   loan_id                  800000 non-null  int64
 1   customer_segment         800000 non-null  str
 2   sanction_amount          800000 non-null  int64
 3   outstanding_principal    800000 non-null  int64
 4   interest_rate            800000 non-null  float64
 5   repricing_frequency      800000 non-null  str
 6   prepayment_option        800000 non-null  str
 7   collateral_type          800000 non-null  str
 8   region                   800000 non-null  str
 9   tenure_months            800000 non-null  int64
 10  alm_bucket               800000 non-null  str
 11  monthly_interest_income  800000 non-null  float64
 12  total_loan_inflow        800000 non-null  float64
dtypes: float64(3), int64(4), str(6)
memory usage: 79.3 MB

In [118]:
df_macro.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             600000 non-null  datetime64[us]
 1   repo_rate        600000 non-null  float64
 2   gsec_10y         600000 non-null  float64
 3   cp_rate          600000 non-null  float64
 4   inflation_cpi    600000 non-null  float64
 5   liquidity_index  600000 non-null  float64
 6   usd_inr          600000 non-null  float64
dtypes: datetime64[us](1), float64(6)
memory usage: 32.0 MB

In [132]:
df_macro['repo_rate']

0         6.32
1         5.16
2         4.53
3         5.41
4         4.87
          ...
599995    6.71
599996    5.59
599997    4.78
599998    6.81
599999    6.27
Name: repo_rate, Length: 600000, dtype: float64

In [121]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   borrowing_id            200000 non-null  int64
 1   funding_source          200000 non-null  str
 2   cost_of_funds           200000 non-null  float64
 3   maturity_bucket         200000 non-null  str
 4   interest_reset_type     200000 non-null  str
 5   borrowing_amount        200000 non-null  int64
 6   rollover_risk_score     200000 non-null  float64
 7   total_borrowing_amount  200000 non-null  int64
dtypes: float64(2), int64(3), str(3)
memory usage: 12.2 MB

In [122]:
df_borr['cost_of_funds']

0         9.07
1         8.69
2         7.46
3         8.45
4         7.56
          ...
199995    5.65
199996    9.38
199997    9.39
199998    5.33
199999    9.93
Name: cost_of_funds, Length: 200000, dtype: float64

In [123]:
df_loan['alm_bucket'] = df_loan['alm_bucket'].str.lower().str.strip()

In [124]:
df_loan['alm_bucket']

0         1y+
1         1y+
2         1y+
3         1y+
4         1y+
         ...
799995    1y+
799996    1y+
799997    1y+
799998    1y+
799999    1y+
Name: alm_bucket, Length: 800000, dtype: str

In [125]:
alm_bucket_exposure = df_loan['alm_bucket']

In [126]:
alm_bucket_exposure

0         1y+
1         1y+
2         1y+
3         1y+
4         1y+
         ...
799995    1y+
799996    1y+
799997    1y+
799998    1y+
799999    1y+
Name: alm_bucket, Length: 800000, dtype: str

In [135]:
treasury_master_dataset = df_cash[['date']].copy()

In [136]:
treasury_master_dataset['total_loan_inflows'] = df_loan['total_loan_inflow']

In [137]:
treasury_master_dataset['total_borrowing_outflows'] = df_borr['total_borrowing_amount']

In [138]:
treasury_master_dataset['cost_of_funds'] = df_borr['cost_of_funds']
treasury_master_dataset['repo_rate'] = df_macro['repo_rate']

In [139]:
treasury_master_dataset['alm_bucket'] = df_loan['alm_bucket']

In [140]:
treasury_master_dataset['net_liquidity_position'] = (
    treasury_master_dataset['total_loan_inflows'] -
    treasury_master_dataset['total_borrowing_outflows']
)

In [141]:
treasury_master_dataset

,date,total_loan_inflows,total_borrowing_outflows,cost_of_funds,repo_rate,alm_bucket,net_liquidity_position
0,2023-07-09,1.451079e+06,5.093761e+12,9.07,6.32,1y+,-5.093759e+12
1,2022-01-10,1.071684e+06,5.093761e+12,8.69,5.16,1y+,-5.093759e+12
2,2024-09-30,3.544427e+06,5.093761e+12,7.46,4.53,1y+,-5.093757e+12
3,2023-10-07,4.782148e+06,5.093761e+12,8.45,5.41,1y+,-5.093756e+12
4,2024-05-25,8.913807e+05,5.093761e+12,7.56,4.87,1y+,-5.093760e+12
...,...,...,...,...,...,...,...
299995,2024-12-07,3.125258e+06,NaN,NaN,6.48,1y+,NaN
299996,2023-01-05,3.191235e+06,NaN,NaN,5.54,1y+,NaN
299997,2024-09-08,1.115557e+06,NaN,NaN,6.26,1y+,NaN
299998,2022-07-08,1.593192e+06,NaN,NaN,4.58,1y+,NaN
299999,2022-02-22,1.849498e+05,NaN,NaN,6.26,1y+,NaN

In [ ]:
treasury_master_dataset.to_parquet('C:/Users/admin/Downloads/phase 3/Untitled4.ipynb.parquet')