In [5]:
import pandas as pd
df_loan = pd.read_csv("C:/Users/admin/Downloads/datasets/loan_portfolio_dataset.csv")

In [6]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_id                800000 non-null  int64
 1   customer_segment       800000 non-null  str
 2   sanction_amount        800000 non-null  int64
 3   outstanding_principal  800000 non-null  int64
 4   interest_rate          800000 non-null  float64
 5   repricing_frequency    800000 non-null  str
 6   prepayment_option      800000 non-null  str
 7   collateral_type        800000 non-null  str
 8   region                 800000 non-null  str
 9   tenure_months          800000 non-null  int64
dtypes: float64(1), int64(4), str(5)
memory usage: 84.3 MB

In [7]:
import pandas as pd
df_borr = pd.read_csv("C:/Users/admin/Downloads/datasets/borrowing_funding_dataset.csv")

In [8]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   borrowing_id         200000 non-null  int64
 1   funding_source       200000 non-null  str
 2   cost_of_funds        200000 non-null  float64
 3   maturity_bucket      200000 non-null  str
 4   interest_reset_type  200000 non-null  str
 5   borrowing_amount     200000 non-null  int64
 6   rollover_risk_score  200000 non-null  float64
dtypes: float64(2), int64(2), str(3)
memory usage: 14.1 MB

In [9]:
import pandas as pd
df_cash = pd.read_csv("C:/Users/admin/Downloads/datasets/daily_cashflow_dataset.csv")

In [10]:
df_cash.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  str
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
dtypes: int64(3), str(3)
memory usage: 23.4 MB

In [3]:
import pandas as pd
df_macro = pd.read_csv("C:/Users/admin/Downloads/datasets/market_macro_dataset.csv")

In [4]:
df_macro.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             600000 non-null  str
 1   repo_rate        600000 non-null  float64
 2   gsec_10y         600000 non-null  float64
 3   cp_rate          600000 non-null  float64
 4   inflation_cpi    600000 non-null  float64
 5   liquidity_index  600000 non-null  float64
 6   usd_inr          600000 non-null  float64
dtypes: float64(6), str(1)
memory usage: 37.8 MB

In [13]:
import pandas as pd
import ipywidgets as widgets

date_picker = widgets.SelectionRangeSlider(
    options=sorted(df_cash['date'].unique()),
    description='date'
)

segment_filter = widgets.Dropdown(
    options=['All'] + sorted(df_loan['customer_segment'].dropna().unique().tolist()),
    description='segment'
)

region_filter = widgets.Dropdown(
    options=['All'] + sorted(df_loan['region'].dropna().unique().tolist()),
    description='region'
)

funding_filter = widgets.Dropdown(
    options=['All'] + sorted(df_borr['funding_source'].dropna().unique().tolist()),
    description='funding'
)

In [14]:
date_picker

SelectionRangeSlider(description='date', index=(0, 0), options=('2022-01-01', '2022-01-02', '2022-01-03', '202…

In [15]:
segment_filter

Dropdown(description='segment', options=('All', 'Corporate', 'Retail', 'SME'), value='All')

In [16]:
region_filter

Dropdown(description='region', options=('All', 'Central', 'East', 'North', 'South', 'West'), value='All')

In [17]:
funding_filter

Dropdown(description='funding', options=('All', 'Bank Line', 'Commercial Paper', 'NCD', 'Term Loan'), value='A…

In [18]:
collateral_filter = widgets.Dropdown(
    options=['All'] + sorted(df_loan['collateral_type'].dropna().unique().tolist()),
    description='collateral'
)

maturity_filter = widgets.Dropdown(
    options=['All'] + sorted(df_borr['maturity_bucket'].dropna().unique().tolist()),
    description='maturity'
)

repricing_filter = widgets.Dropdown(
    options=['All'] + sorted(df_loan['repricing_frequency'].dropna().unique().tolist()),
    description='repricing'
)

In [19]:
collateral_filter

Dropdown(description='collateral', options=('All', 'Secured', 'Unsecured'), value='All')

In [20]:
maturity_filter

Dropdown(description='maturity', options=('All', '1M', '1Y', '3M', '3Y', '6M'), value='All')

In [21]:
repricing_filter

Dropdown(description='repricing', options=('All', 'Half-Yearly', 'Monthly', 'Quarterly'), value='All')

In [22]:
view_toggle = widgets.ToggleButtons(
    options=['Daily', 'Monthly'],
    description='View'
)

value_toggle = widgets.ToggleButtons(
    options=['Absolute', 'Percentage'],
    description='Values'
)

In [23]:
view_toggle

ToggleButtons(description='View', options=('Daily', 'Monthly'), value='Daily')

In [24]:
value_toggle

ToggleButtons(description='Values', options=('Absolute', 'Percentage'), value='Absolute')

In [24]:
def filter_data(df_loan, df_borr):
    df_lo = df_loan.copy()
    df_b = df_borr.copy()

    # Segment filter
    if segment_filter.value != 'All':
        df_lo = df_lo[df_lo['customer_segment'] ==customer_segment_filter.value]

    # Region filter
    if region_filter.value != 'All':
        df_lo= df_lo[df_lo['region'] == region_filter.value]

    # Funding filter (for borrowing dataset)
    if funding_filter.value != 'All':
        df_b = df_b[df_b['funding_source'] == funding_filter.value]

    return df_lo, df_b

In [58]:
def show_customer_segment_view(df_lo):segment_summary = df_loan.groupby('customer_segment')['sanction_amount'].sum().reset_index()

In [40]:
def show_loan_level(df_lo):display(df_loan[['loan_id','customer_segment','sanction_amount','region']])

In [43]:
def show_borrowing(df_b):display(df_borr[['borrowing_amount','funding_source','borrowing_amount','maturity_bucket']])

In [25]:
segment_summary = df_loan.groupby('customer_segment')['sanction_amount'].sum().reset_index()
segment_summary

  customer_segment  sanction_amount
0        Corporate     673370753101
1           Retail     673314928313
2              SME     671724790091

In [26]:
selected_segment = 'Retail'

df_loan_segment = df_loan[df_loan['customer_segment'] == selected_segment]
df_loan_segment

,loan_id,customer_segment,sanction_amount,outstanding_principal,interest_rate,repricing_frequency,prepayment_option,collateral_type,region,tenure_months
1,2,Retail,2598113,1509414,8.52,Half-Yearly,Yes,Secured,North,18
4,5,Retail,3840012,1414890,7.56,Monthly,Yes,Secured,North,91
5,6,Retail,3744016,661621,13.63,Half-Yearly,Yes,Unsecured,West,60
12,13,Retail,1934059,834429,12.28,Monthly,No,Secured,Central,67
15,16,Retail,3448422,1048557,13.77,Monthly,No,Unsecured,Central,206
...,...,...,...,...,...,...,...,...,...,...
799978,799979,Retail,2973224,3481795,8.88,Quarterly,Yes,Secured,West,83
799983,799984,Retail,4131934,2157703,14.70,Monthly,No,Secured,Central,203
799996,799997,Retail,4514389,3717405,11.78,Quarterly,Yes,Secured,East,139
799997,799998,Retail,1811402,1035235,7.23,Quarterly,No,Secured,North,15
799998,799999,Retail,1589116,572950,8.15,Monthly,Yes,Secured,Central,109

In [28]:
segment_fun = df_borr.groupby('funding_source')['borrowing_amount'].sum().reset_index()
segment_fun

     funding_source  borrowing_amount
0         Bank Line     1280151079223
1  Commercial Paper     1272265925903
2               NCD     1266729837342
3         Term Loan     1274613686226

In [ ]:
selected_segment = 'Retail'

df_loan_segment = df_loan[df_loan['customer_segment'] == selected_segment]
df_loan_segment

In [33]:
selected_funding = 'Bank Line'

df_borr_funding_source = df_borr[df_borr['funding_source'] == selected_funding]
df_borr_funding_source

,borrowing_id,funding_source,cost_of_funds,maturity_bucket,interest_reset_type,borrowing_amount,rollover_risk_score
2,3,Bank Line,7.46,6M,Floating,21925818,0.3430
6,7,Bank Line,10.85,1M,Floating,26523391,0.1843
7,8,Bank Line,10.51,6M,Fixed,19858507,0.0104
15,16,Bank Line,9.75,3Y,Fixed,2643360,0.9459
21,22,Bank Line,6.86,1Y,Floating,48953821,0.8380
...,...,...,...,...,...,...,...
199981,199982,Bank Line,5.91,1M,Fixed,47672587,0.2327
199985,199986,Bank Line,5.18,3M,Fixed,12659972,0.4405
199990,199991,Bank Line,10.79,3M,Fixed,46061925,0.7844
199993,199994,Bank Line,8.89,3M,Fixed,22801971,0.6632
199996,199997,Bank Line,9.38,3M,Fixed,10606928,0.0016

In [35]:
def color_liquidity(val):
    if val < 0:
        return 'background-color: red; color: white'
    elif val < 50:
        return 'background-color: yellow; color: black'
    else:
        return 'background-color: green; color: white'

In [45]:
def business_interpretation(val):
    if val < 0:
        return "Immediate risk | Need funding"
    else:
        return "Healthy"

df_macro['business_interpretation'] = df_macro['liquidity_index'].apply(business_interpretation)

df_macro[['date', 'liquidity_index', 'business_interpretation']].head()

         date  liquidity_index        business_interpretation
0  2023-05-04           -0.360  Immediate risk | Need funding
1  2024-09-16           -0.171  Immediate risk | Need funding
2  2024-08-14            0.991                        Healthy
3  2024-04-23            0.188                        Healthy
4  2024-02-10            1.748                        Healthy

In [6]:
def highlight_risk(val):
    if val < 0:
        return 'background-color: red; color: white'
    else:
        return ''

df_macro.head(5).style.map(highlight_risk, subset=['liquidity_index'])

In [47]:
df_cash.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  str
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
dtypes: int64(3), str(3)
memory usage: 23.4 MB

In [48]:
def liquidity_gap_rule(row):
    if row['outflow_type'] > row['inflow_type']:
        return "Liquidity gap forming"
    else:
        return "No gap"

In [51]:
df_cash['liquidity_gap_status'] = df_cash.apply(liquidity_gap_rule, axis=1)

df_cash[['inflow_type', 'outflow_type', 'liquidity_gap_status']]

       inflow_type         outflow_type   liquidity_gap_status
0             Fees     Interest Payment  Liquidity gap forming
1              EMI  Operational Expense  Liquidity gap forming
2             Fees  Principal Repayment  Liquidity gap forming
3             Fees  Operational Expense  Liquidity gap forming
4             Fees     Interest Payment  Liquidity gap forming
...            ...                  ...                    ...
299995         EMI     Interest Payment  Liquidity gap forming
299996         EMI     Interest Payment  Liquidity gap forming
299997         EMI     Interest Payment  Liquidity gap forming
299998         EMI     Interest Payment  Liquidity gap forming
299999        Fees  Operational Expense  Liquidity gap forming

[300000 rows x 3 columns]

In [56]:
df_borr.cost_of_funds

0         9.07
1         8.69
2         7.46
3         8.45
4         7.56
          ...
199995    5.65
199996    9.38
199997    9.39
199998    5.33
199999    9.93
Name: cost_of_funds, Length: 200000, dtype: float64

In [54]:
df_borr['prev_cost_of_funds'] = df_borr['cost_of_funds'].shift(1)

import numpy as np

df_borr['cost_trend'] = np.where(df_borr['cost_of_funds'] > df_borr['prev_cost_of_funds'],
    "Market stress / bad funding mix",
    "Stable"
)

In [55]:
df_borr['cost_trend']

0                                  Stable
1                                  Stable
2                                  Stable
3         Market stress / bad funding mix
4                                  Stable
                       ...
199995                             Stable
199996    Market stress / bad funding mix
199997    Market stress / bad funding mix
199998                             Stable
199999    Market stress / bad funding mix
Name: cost_trend, Length: 200000, dtype: str

In [57]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   borrowing_id         200000 non-null  int64
 1   funding_source       200000 non-null  str
 2   cost_of_funds        200000 non-null  float64
 3   maturity_bucket      200000 non-null  str
 4   interest_reset_type  200000 non-null  str
 5   borrowing_amount     200000 non-null  int64
 6   rollover_risk_score  200000 non-null  float64
 7   prev_cost_of_funds   199999 non-null  float64
 8   cost_trend           200000 non-null  str
dtypes: float64(3), int64(2), str(4)
memory usage: 20.6 MB

In [59]:
df_borr[['cost_of_funds', 'prev_cost_of_funds','cost_trend']]

        cost_of_funds  prev_cost_of_funds                       cost_trend
0                9.07                 NaN                           Stable
1                8.69                9.07                           Stable
2                7.46                8.69                           Stable
3                8.45                7.46  Market stress / bad funding mix
4                7.56                8.45                           Stable
...               ...                 ...                              ...
199995           5.65               10.74                           Stable
199996           9.38                5.65  Market stress / bad funding mix
199997           9.39                9.38  Market stress / bad funding mix
199998           5.33                9.39                           Stable
199999           9.93                5.33  Market stress / bad funding mix

[200000 rows x 3 columns]

In [60]:
df_macro.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 8 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   date                     600000 non-null  str
 1   repo_rate                600000 non-null  float64
 2   gsec_10y                 600000 non-null  float64
 3   cp_rate                  600000 non-null  float64
 4   inflation_cpi            600000 non-null  float64
 5   liquidity_index          600000 non-null  float64
 6   usd_inr                  600000 non-null  float64
 7   business_interpretation  600000 non-null  str
dtypes: float64(6), str(2)
memory usage: 52.6 MB

In [64]:
import numpy as np

threshold = df_cash['variance'] 

df_cash['variance_flag'] = np.where(
    df_cash['variance'] > threshold,
    "Forecasting unreliable",
    "Stable"
)

In [65]:
df_cash['variance_flag']

0         Stable
1         Stable
2         Stable
3         Stable
4         Stable
           ...
299995    Stable
299996    Stable
299997    Stable
299998    Stable
299999    Stable
Name: variance_flag, Length: 300000, dtype: str

In [66]:
df_cash[['variance', 'variance_flag']]

   variance variance_flag
0   -347259        Stable
1    663314        Stable
2   3117630        Stable
3  -3884040        Stable
4  -1939392        Stable