week 2,phase1

In [1]:
import pandas as pd
df_loan= pd.read_csv("C:/Users/admin/Downloads/datasets/loan_portfolio_dataset.csv")

In [2]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_id                800000 non-null  int64
 1   customer_segment       800000 non-null  str
 2   sanction_amount        800000 non-null  int64
 3   outstanding_principal  800000 non-null  int64
 4   interest_rate          800000 non-null  float64
 5   repricing_frequency    800000 non-null  str
 6   prepayment_option      800000 non-null  str
 7   collateral_type        800000 non-null  str
 8   region                 800000 non-null  str
 9   tenure_months          800000 non-null  int64
dtypes: float64(1), int64(4), str(5)
memory usage: 84.3 MB

In [3]:
df_loan.shape

(800000, 10)

In [5]:
df_loan.dtypes

loan_id                    int64
customer_segment             str
sanction_amount            int64
outstanding_principal      int64
interest_rate            float64
repricing_frequency          str
prepayment_option            str
collateral_type              str
region                       str
tenure_months              int64
dtype: object

In [6]:
df_loan.describe()

,loan_id,sanction_amount,outstanding_principal,interest_rate,tenure_months
count,800000.000000,8.000000e+05,8.000000e+05,800000.000000,800000.000000
mean,400000.500000,2.523013e+06,2.004313e+06,12.496878,125.485942
std,230940.252013,1.430761e+06,1.151454e+06,3.175649,65.827576
min,1.000000,5.000600e+04,1.002000e+04,7.000000,12.000000
25%,200000.750000,1.282186e+06,1.007734e+06,9.750000,68.000000
50%,400000.500000,2.520272e+06,2.003104e+06,12.500000,126.000000
75%,600000.250000,3.762831e+06,3.002133e+06,15.240000,182.000000
max,800000.000000,4.999998e+06,3.999995e+06,18.000000,239.000000

In [7]:
df_loan.isnull().sum().sort_values

<bound method Series.sort_values of loan_id                  0
customer_segment         0
sanction_amount          0
outstanding_principal    0
interest_rate            0
repricing_frequency      0
prepayment_option        0
collateral_type          0
region                   0
tenure_months            0
dtype: int64>

In [13]:
df_loan['revenue']=df_loan['outstanding_principal'] * df_loan['interest_rate']* df_loan['tenure_months']/12

In [14]:
df_loan['revenue']

0         2.089554e+08
1         1.929031e+07
2         1.807658e+08
3         1.004251e+08
4         8.111564e+07
              ...
799995    1.739535e+08
799996    5.072461e+08
799997    9.355936e+06
799998    4.241501e+07
799999    3.819031e+08
Name: revenue, Length: 800000, dtype: float64

In [15]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_id                800000 non-null  int64
 1   customer_segment       800000 non-null  str
 2   sanction_amount        800000 non-null  int64
 3   outstanding_principal  800000 non-null  int64
 4   interest_rate          800000 non-null  float64
 5   repricing_frequency    800000 non-null  str
 6   prepayment_option      800000 non-null  str
 7   collateral_type        800000 non-null  str
 8   region                 800000 non-null  str
 9   tenure_months          800000 non-null  int64
 10  revenue                800000 non-null  float64
dtypes: float64(2), int64(4), str(5)
memory usage: 90.4 MB

In [19]:
for col in cat_cols:
    print(f"\n{col}")
    print(df_loan[col].value_counts())

customer_segment
customer_segment
Retail       266863
Corporate    266650
SME          266487
Name: count, dtype: int64

repricing_frequency
repricing_frequency
Quarterly      267074
Monthly        266538
Half-Yearly    266388
Name: count, dtype: int64

prepayment_option
prepayment_option
No     400388
Yes    399612
Name: count, dtype: int64

collateral_type
collateral_type
Secured      400160
Unsecured    399840
Name: count, dtype: int64

region
region
Central    160595
East       160584
South      160023
West       159944
North      158854
Name: count, dtype: int64

In [20]:
df_loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_id                800000 non-null  int64
 1   customer_segment       800000 non-null  str
 2   sanction_amount        800000 non-null  int64
 3   outstanding_principal  800000 non-null  int64
 4   interest_rate          800000 non-null  float64
 5   repricing_frequency    800000 non-null  str
 6   prepayment_option      800000 non-null  str
 7   collateral_type        800000 non-null  str
 8   region                 800000 non-null  str
 9   tenure_months          800000 non-null  int64
 10  revenue                800000 non-null  float64
dtypes: float64(2), int64(4), str(5)
memory usage: 90.4 MB

In [22]:
df_loan.describe()

,loan_id,sanction_amount,outstanding_principal,interest_rate,tenure_months,revenue
count,800000.000000,8.000000e+05,8.000000e+05,800000.000000,800000.000000,8.000000e+05
mean,400000.500000,2.523013e+06,2.004313e+06,12.496878,125.485942,2.619127e+08
std,230940.252013,1.430761e+06,1.151454e+06,3.175649,65.827576,2.349814e+08
min,1.000000,5.000600e+04,1.002000e+04,7.000000,12.000000,1.092516e+05
25%,200000.750000,1.282186e+06,1.007734e+06,9.750000,68.000000,7.743910e+07
50%,400000.500000,2.520272e+06,2.003104e+06,12.500000,126.000000,1.923210e+08
75%,600000.250000,3.762831e+06,3.002133e+06,15.240000,182.000000,3.830296e+08
max,800000.000000,4.999998e+06,3.999995e+06,18.000000,239.000000,1.402865e+09

In [23]:
df_loan.isnull().sum()

loan_id                  0
customer_segment         0
sanction_amount          0
outstanding_principal    0
interest_rate            0
repricing_frequency      0
prepayment_option        0
collateral_type          0
region                   0
tenure_months            0
revenue                  0
dtype: int64

borrowing dataset

In [24]:
import pandas as pd
df_borr= pd.read_csv("C:/Users/admin/Downloads/datasets/borrowing_funding_dataset.csv")

In [25]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   borrowing_id         200000 non-null  int64
 1   funding_source       200000 non-null  str
 2   cost_of_funds        200000 non-null  float64
 3   maturity_bucket      200000 non-null  str
 4   interest_reset_type  200000 non-null  str
 5   borrowing_amount     200000 non-null  int64
 6   rollover_risk_score  200000 non-null  float64
dtypes: float64(2), int64(2), str(3)
memory usage: 14.1 MB

In [26]:
df_borr.describe()

        borrowing_id  cost_of_funds  borrowing_amount  rollover_risk_score
count  200000.000000  200000.000000      2.000000e+05        200000.000000
mean   100000.500000       8.506839      2.546880e+07             0.500942
std     57735.171256       2.021255      1.410020e+07             0.288961
min         1.000000       5.000000      1.000247e+06             0.000000
25%     50000.750000       6.750000      1.323955e+07             0.250400
50%    100000.500000       8.510000      2.549018e+07             0.501700
75%    150000.250000      10.250000      3.761771e+07             0.751200
max    200000.000000      12.000000      4.999963e+07             1.000000

In [28]:
df_borr.dtypes

borrowing_id             int64
funding_source             str
cost_of_funds          float64
maturity_bucket            str
interest_reset_type        str
borrowing_amount         int64
rollover_risk_score    float64
dtype: object

In [29]:
df_borr.shape

(200000, 7)

In [30]:
df_borr.isnull().sum().sort_values

<bound method Series.sort_values of borrowing_id           0
funding_source         0
cost_of_funds          0
maturity_bucket        0
interest_reset_type    0
borrowing_amount       0
rollover_risk_score    0
dtype: int64>

In [32]:
df_borr['expense']=(df_borr['borrowing_amount'] * df_borr['cost_of_funds'])

In [33]:
df_borr['expense']

0         8.098346e+07
1         2.723807e+08
2         1.635666e+08
3         9.917954e+07
4         3.284533e+08
              ...
199995    1.070654e+08
199996    9.949298e+07
199997    3.150187e+08
199998    2.377600e+08
199999    1.390982e+08
Name: expense, Length: 200000, dtype: float64

In [34]:
df_borr.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   borrowing_id         200000 non-null  int64
 1   funding_source       200000 non-null  str
 2   cost_of_funds        200000 non-null  float64
 3   maturity_bucket      200000 non-null  str
 4   interest_reset_type  200000 non-null  str
 5   borrowing_amount     200000 non-null  int64
 6   rollover_risk_score  200000 non-null  float64
 7   expense              200000 non-null  float64
dtypes: float64(3), int64(2), str(3)
memory usage: 15.6 MB

In [42]:
df_borr.describe()

,borrowing_id,cost_of_funds,borrowing_amount,rollover_risk_score,expense
count,200000.000000,200000.000000,2.000000e+05,200000.000000,2.000000e+05
mean,100000.500000,8.506839,2.546880e+07,0.500942,2.166746e+08
std,57735.171256,2.021255,1.410020e+07,0.288961,1.335294e+08
min,1.000000,5.000000,1.000247e+06,0.000000,5.044124e+06
25%,50000.750000,6.750000,1.323955e+07,0.250400,1.059068e+08
50%,100000.500000,8.510000,2.549018e+07,0.501700,2.039696e+08
75%,150000.250000,10.250000,3.761771e+07,0.751200,3.086358e+08
max,200000.000000,12.000000,4.999963e+07,1.000000,5.979038e+08

In [43]:
df_borr.isnull().sum()

borrowing_id           0
funding_source         0
cost_of_funds          0
maturity_bucket        0
interest_reset_type    0
borrowing_amount       0
rollover_risk_score    0
expense                0
dtype: int64

cash flowdataset phase1

In [44]:
import pandas as pd
df_cash= pd.read_csv("C:/Users/admin/Downloads/datasets/daily_cashflow_dataset.csv")

In [45]:
df_cash.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  str
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
dtypes: int64(3), str(3)
memory usage: 23.4 MB

In [46]:
df_cash.describe()

       expected_amount  actual_amount      variance
count     3.000000e+05   3.000000e+05  3.000000e+05
mean      2.502234e+06   2.508259e+06  6.024329e+03
std       1.439052e+06   1.439805e+06  2.035640e+06
min       1.000400e+04   1.000100e+04 -4.971602e+06
25%       1.253227e+06   1.262189e+06 -1.454054e+06
50%       2.502554e+06   2.514194e+06  5.525500e+03
75%       3.746451e+06   3.755466e+06  1.467227e+06
max       4.999994e+06   4.999944e+06  4.977697e+06

In [48]:
df_cash.shape

(300000, 6)

In [49]:
df_cash.dtypes

date                 str
inflow_type          str
outflow_type         str
expected_amount    int64
actual_amount      int64
variance           int64
dtype: object

In [50]:
df_cash.dtypes


num_cols = df_cash.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df_cash.select_dtypes(include=['object', 'category']).columns

print("Numeric columns:", num_cols)
print("Categorical columns:", cat_cols)

Numeric columns: Index(['expected_amount', 'actual_amount', 'variance'], dtype='str')
Categorical columns: Index(['date', 'inflow_type', 'outflow_type'], dtype='str')

C:\Users\admin\AppData\Local\Temp\ipykernel_4816\2934881162.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df_cash.select_dtypes(include=['object', 'category']).columns

In [51]:
for col in cat_cols:
    print(f"\n{col}")
    print(df_cash[col].value_counts())

date
date
2022-12-10    326
2024-11-08    325
2024-12-04    323
2022-02-19    321
2024-12-06    320
             ...
2024-11-18    230
2023-02-08    229
2024-03-26    226
2024-12-20    222
2023-08-21    221
Name: count, Length: 1095, dtype: int64

inflow_type
inflow_type
Prepayment    100107
EMI           100060
Fees           99833
Name: count, dtype: int64

outflow_type
outflow_type
Principal Repayment    100296
Operational Expense    100071
Interest Payment        99633
Name: count, dtype: int64

In [53]:
df_cash.isnull().sum()

date               0
inflow_type        0
outflow_type       0
expected_amount    0
actual_amount      0
variance           0
dtype: int64

In [54]:
df_cash.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             300000 non-null  str
 1   inflow_type      300000 non-null  str
 2   outflow_type     300000 non-null  str
 3   expected_amount  300000 non-null  int64
 4   actual_amount    300000 non-null  int64
 5   variance         300000 non-null  int64
dtypes: int64(3), str(3)
memory usage: 23.4 MB

In [55]:
df_cash.describe()

       expected_amount  actual_amount      variance
count     3.000000e+05   3.000000e+05  3.000000e+05
mean      2.502234e+06   2.508259e+06  6.024329e+03
std       1.439052e+06   1.439805e+06  2.035640e+06
min       1.000400e+04   1.000100e+04 -4.971602e+06
25%       1.253227e+06   1.262189e+06 -1.454054e+06
50%       2.502554e+06   2.514194e+06  5.525500e+03
75%       3.746451e+06   3.755466e+06  1.467227e+06
max       4.999994e+06   4.999944e+06  4.977697e+06

market macro dataset

In [56]:
import pandas as pd
df_macro= pd.read_csv("C:/Users/admin/Downloads/datasets/market_macro_dataset.csv")

In [57]:
df_macro.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             600000 non-null  str
 1   repo_rate        600000 non-null  float64
 2   gsec_10y         600000 non-null  float64
 3   cp_rate          600000 non-null  float64
 4   inflation_cpi    600000 non-null  float64
 5   liquidity_index  600000 non-null  float64
 6   usd_inr          600000 non-null  float64
dtypes: float64(6), str(1)
memory usage: 37.8 MB

In [58]:
df_macro.describe()

,repo_rate,gsec_10y,cp_rate,inflation_cpi,liquidity_index,usd_inr
count,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000
mean,5.749853,6.999804,7.000133,5.500726,0.000235,80.005830
std,1.009055,0.865009,1.154134,1.443123,1.156002,5.775332
min,4.000000,5.500000,5.000000,3.000000,-2.000000,70.000000
25%,4.880000,6.250000,6.000000,4.250000,-1.003000,75.000000
50%,5.750000,7.000000,7.000000,5.500000,0.002000,80.000000
75%,6.620000,7.750000,8.000000,6.750000,1.003000,85.010000
max,7.500000,8.500000,9.000000,8.000000,2.000000,90.000000

In [59]:
df_macro.shape

(600000, 7)

In [60]:
df_macro.dtypes

date                   str
repo_rate          float64
gsec_10y           float64
cp_rate            float64
inflation_cpi      float64
liquidity_index    float64
usd_inr            float64
dtype: object

In [63]:
for col in cat_cols:
    print(f"\n{col}")
    print(df_macro[col].value_counts())

date
date
2022-02-14    624
2022-07-21    622
2023-09-11    619
2022-03-16    618
2023-07-29    617
             ...
2023-12-22    490
2023-04-08    488
2024-06-21    483
2023-02-27    481
2022-04-29    475
Name: count, Length: 1095, dtype: int64

In [64]:
df_macro.dtypes

num_cols = df_macro.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df_macro.select_dtypes(include=['object', 'category']).columns

print("Numeric columns:", num_cols)
print("Categorical columns:", cat_cols)

Numeric columns: Index(['repo_rate', 'gsec_10y', 'cp_rate', 'inflation_cpi', 'liquidity_index',
       'usd_inr'],
      dtype='str')
Categorical columns: Index(['date'], dtype='str')

C:\Users\admin\AppData\Local\Temp\ipykernel_4816\2827493496.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df_macro.select_dtypes(include=['object', 'category']).columns

In [65]:
df_macro.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             600000 non-null  str
 1   repo_rate        600000 non-null  float64
 2   gsec_10y         600000 non-null  float64
 3   cp_rate          600000 non-null  float64
 4   inflation_cpi    600000 non-null  float64
 5   liquidity_index  600000 non-null  float64
 6   usd_inr          600000 non-null  float64
dtypes: float64(6), str(1)
memory usage: 37.8 MB

In [66]:
df_macro.describe()

,repo_rate,gsec_10y,cp_rate,inflation_cpi,liquidity_index,usd_inr
count,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000
mean,5.749853,6.999804,7.000133,5.500726,0.000235,80.005830
std,1.009055,0.865009,1.154134,1.443123,1.156002,5.775332
min,4.000000,5.500000,5.000000,3.000000,-2.000000,70.000000
25%,4.880000,6.250000,6.000000,4.250000,-1.003000,75.000000
50%,5.750000,7.000000,7.000000,5.500000,0.002000,80.000000
75%,6.620000,7.750000,8.000000,6.750000,1.003000,85.010000
max,7.500000,8.500000,9.000000,8.000000,2.000000,90.000000

In [67]:
df_macro.isnull().sum()

date               0
repo_rate          0
gsec_10y           0
cp_rate            0
inflation_cpi      0
liquidity_index    0
usd_inr            0
dtype: int64